### ISSUE TITLE
Not clear how to manage ExternalEmailAddress wen using ADConnect

### ISSUE THREAD

**Issue by antede** [MicrosoftDocs/OfficeDocs-Exchange#1045]
When AD is synchronized with ADConnect, we need to populate the targetAddress (in AD) in order to convert users to mailusers and set the ExternalEmailAddress as required by the migration process. It is not clear how can the migration process remove the ExternalEmailAddress from the object when converting the mailuser to a mailbox user. Doing a manual test, despite the ExternalEmailAddress is not more visible after converting the mailuser to a mailbox, the attribute is still enforced via ADConnect and the incoming email gets forwarded to Gsuite address. So it seems we are required to clear the targetAddress from AD in order to complete the migration. Can you please confirm or provide a better detail on this scenario? Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by wrall** [comment]
Hi @antede,

During the "provisioning" step of the Migration, it converts the MailUser into a Mailbox and in doing so it moves the targetAddress value within the ExternalEmailAddress property into the ForwardingSmtpAddress property.  Later, when the Migration is being completed/finalized, the Migration process clears the ForwardingSmtpAddress property from the target Mailbox and applies the Gmail forwarding setting to the G Suite user.

> the attribute is still enforced via ADConnect

Are you sure about this?  I thought that ADConnect wouldn't apply a targetAddress to a Mailbox user...  Maybe it depends on your settings?

Thanks

**Comment by scanum** [comment]
@antede  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by antede** [comment]
Hi. Figured out this was an environment-specific issue. In this case i had a tenant with Hybrid Exchange and Centralized Transport enabled. In such case, when the message is routed trough on-premises Exchange, it hits the mailuser with the targetAddress defined in AD. Testing on a different tenant without Hybrid or just disabling the centralized transport did not reproduce the issue. Thanks for your help in understanding!

**Comment by msbemba** [comment]
@antede Thank you for the feedback.  You are correct the document refers to a migration without Hybrid setup.  Hope this helps!

Thanks
Sri

**Comment by scanum** [comment]
@antede Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by neonad** [comment]
Hi @antede,

In the article it states that we need to disable directory synchronization in order to support converting mailuser to mailbox during the migration? However, if we disable directory sync, it will take up another 72 hours to restart it, which i believe not a suitable solution. Can you let me know whether this worked exactly like mentioned by @wrall with AADConnect in place?

_During the "provisioning" step of the Migration, it converts the MailUser into a Mailbox and in doing so it moves the targetAddress value within the ExternalEmailAddress property into the ForwardingSmtpAddress property. Later, when the Migration is being completed/finalized, the Migration process clears the ForwardingSmtpAddress property from the target Mailbox and applies the Gmail forwarding setting to the G Suite user. This ensures that mail flows to the appropriate location throughout the migration process._

Thanks,
Neo
