### ISSUE TITLE
Verify prerequisites

### ISSUE THREAD

**Issue by IdahoR** [MicrosoftDocs/OfficeDocs-Exchange#1098]
Hi, can you please check the Windows Server 2016 prerequisites for Exchange 2016 section?  Item 2b, Microsoft Knowledge Base article KB3206632, is quite old now and appears to have been superseded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e0968e-9590-59a1-83c8-07c218bcf8fd
* Version Independent ID: 42d25a51-bb1a-3d51-75fe-85731236aa04
* Content: [Exchange Server prerequisites, Exchange 2019 system requirements, Exchange 2019 requirements](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/prerequisites?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/prerequisites.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@IdahoR Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by IdahoR** [comment]
Please also clarify the wording of the Note regarding the Visual C++ Redistributable Packages for Visual Studio versions.  It's clear that the Edge role only requires 2012, but does the Mailbox role require BOTH 2012 and 2013 or ONLY 2013?  Thanks.

**Comment by sowjanya365** [comment]
Hi @IdahoR 

Thanks for reaching out!

This particular KB article KB3206632 addressed issue where Azure Active Directory-joined machines after upgrading to Windows 10 Version 1607 cannot sync with Exchange. Microsoft Exchange Server 2016 Setup can't continue because the local computer requires a software update. You'll need to install this update before Exchange 2016 Setup can continue. Did you try installing Exchange 2016 on computers running Windows Server 2016 with the updated KB. Kindly share with us your experience and issues that you've faced. 

And regarding the Visual C++ wordings, mailbox role requires visual studio 2013 version only. Please let us know if you have any queries. Thank you.

**Comment by chrisda** [comment]
OK. I've updated the topic. KB3206632 or KB3213522 can only be installed on fairly old versions of Windows Server 2016 (14393.576 or earlier). Any later version of Windows Server 2016 would already have this update included. This is also verified by the Readiness Check for this specific update in Exchange Setup. If you lack this update, Exchange Setup will call it out, and you won't be able to continue.

Thanks for the feedback.
