### ISSUE TITLE
G Suite IMAP limitations

### ISSUE THREAD

**Issue by djxspike** [MicrosoftDocs/OfficeDocs-Exchange#1100]
Documentation should probably mention G Suite's IMAP limitations (found here: [https://support.google.com/a/answer/1071518?hl=en](https://support.google.com/a/answer/1071518?hl=en))

I had a 21GB mailbox that was taking FOREVER to migrate and would appear "stuck" syncing with no progress for multiple hours.

It wasn't until I discovered via research that G Suite limits the total bandwidth for downloading email via IMAP to 2,500MB per day.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by wrall** [comment]
@djxspike, you're right that G Suite has a total daily allotment for IMAP.  The Migration tool also specifically only migrates up to 2.0 GB per day to avoid having the user accidentally exceed their daily allotment because that allotment is measured across all email clients.

I'll ask the documentation folks about whether we could add a topic on limitations.  Currently some of them are discussed in our [announcement of the feature](https://techcommunity.microsoft.com/t5/Exchange-Team-Blog/Introducing-the-new-migration-experience-from-Google-G-Suite/ba-p/609375), but they aren't included here.

**Comment by djxspike** [comment]
Yeah it would have been helpful during my recent migration to have that disclaimer somewhere in the Microsoft documentation so I could give the client a more accurate timeline.

**Comment by scanum** [comment]
@djxspike Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by msdmaguire** [comment]
@djxspike Thanks for the feedback. We will be adding that limitation info to the article and the change should appear by the end of this month.
