### ISSUE TITLE
Cutover migration

### ISSUE THREAD

**Issue by poynter2** [MicrosoftDocs/OfficeDocs-Exchange#1111]
Hi,
Can you expand on completing a cut-over migration, do we just need to change the MX, then run the batch but dont complete it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@poynter2 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by wrall** [comment]
Hi @poynter2,

The article currently discusses Staged migration, not Cutover.

For a Cutover migration, the steps would be similar, but you would not need to do as many things to set up coexistence between G Suite and O365.  For example, you would skip creating the two sub-domains for mail routing.  Also, when provisioning users, you would provision regular Mailboxes instead of MailUsers.  Besides that, you're correct - you would provision, run the batch and not complete it (just let it get to Synced status), and update the MX record when you're ready for users to start using the target O365 mailboxes instead of the source G Suite mailboxes.

If you had already provisioned MailUsers and started a batch, then you will either need to Complete the MigrationBatch or you will need to clear the ForwardingSmtpAddress from the Mailboxes before updating the MX record.

Thanks
-Will
