### ISSUE TITLE
can License assign as E5 or E3 or EXO P2

### ISSUE THREAD

**Issue by ergautamsharma** [MicrosoftDocs/OfficeDocs-Exchange#1161]
In this article (https://docs.microsoft.com/en-us/exchange/hybrid-deployment/create-cloud-based-archive), advised to assign license as "Exchange Online Archiving for Exchange Server".

**_Expand the list of Office 365 Enterprise licenses, and then assign the Exchange Online Archiving for Exchange Server license, and then save the changes_.**

Can we assign E3 or E5 or EXO P2? 
if yes then it will only enable archive not mailbox. As mailbox is on-premises... is this correct understanding?

**Comment by scanum** [comment]
@ergautamsharma Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by ergautamsharma** [comment]
Hi @scanum can I have update on this??

**Comment by ergautamsharma** [comment]
Hi @scanum can I have update on this??

**Comment by scanum** [comment]
@ergautamsharma We have someone working on this already. We will update you when we have a solution, thanks for your patience.

**Comment by sowjanya365** [comment]
Hi @ergautamsharma 

Thanks for reaching out!

Yes, you can assign. Mailbox can also be provisioned online as cloud-based archive mailbox. If you recall this sentence from the documentation, it states "This is because the cloud-base archive mailbox is created by the process of directory synchronization, where your on-premises Active Directory is synchronized with Azure Active Directory (Azure AD) in Office 365. By default, directory synchronization runs once every 30 minutes."

Hope this clarifies your query. Kindly confirm. Thank you!
