### ISSUE TITLE
Example 2 in New-MailboxDatabase is not available

### ISSUE THREAD

**Issue by TimHL** [MicrosoftDocs/OfficeDocs-Exchange#12]
Under "Get Mailbox Database Properties" this doc refers to Example 2 on the New-MailboxDatabase command reference page, but that page only has Example 1.  Recommend changing the reference to Example 3 on the Get-MailboxDatabase command reference page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 779f13b8-9e22-dcf0-0659-7ee8c864ce07
* Version Independent ID: 6859924b-989a-13c7-64a3-d88266a8e7b3
* Content: [Manage mailbox databases in Exchange 2016](https://docs.microsoft.com/en-us/Exchange/architecture/mailbox-servers/manage-databases)
* Content Source: [Exchange/ExchangeServer/architecture/mailbox-servers/manage-databases.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/mailbox-servers/manage-databases.md)
* Product: **exchange-server-itpro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by kenwith** [comment]
@TimHL - thanks for the catch. Much appreciated. Fixed in this Pull Request: https://github.com/MicrosoftDocs/OfficeDocs-Exchange/pull/14

By the way, the docs are now open source on GitHub and anyone can make an edit. If you are up for making an edit you will show up as a contributor to the docs here: https://github.com/MicrosoftDocs/OfficeDocs-Exchange/graphs/contributors  

If you do decide to submit a Pull Request you can find instructions in the README at the bottom of this repo: https://github.com/MicrosoftDocs/OfficeDocs-SkypeForBusiness  there is also a video.

Either way, it is greatly appreciated that you took the time to submit this issue. Thanks again!
