### ISSUE TITLE
Fix email delivery issues for error code 550 5.7.1 in Exchange Online

### ISSUE THREAD

**Issue by RasTS1** [MicrosoftDocs/OfficeDocs-Exchange#1208]
I just disabled one of the staff member's account on AD and when I was trying to send email to the disabled account for testing I got 
" Your message couldn't be delivered to the recipient because you don't have permission to send to it.
Ask the recipient's email admin to add you to the accept list for the recipient.
For more information, see DSN 5.7.129 Errors in Exchange Online and Office 365." message 

So, checking with the admin group might be one of the solutions. If the user's account disabled or changed the user might be blocked from communicating or getting email.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31a87ae5-749b-2f7a-8662-61c30af24742
* Version Independent ID: f2f6541e-9e10-e30a-7090-6c39e2a756dc
* Content: [Fix email delivery issues for error code 550 5.7.1 in Exchange Online](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-7-1-in-exchange-online?redirectSourcePath=%252farticle%252fda1ff375-f88f-4a3e-b81f-06cdb6ecae3c#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-7-1-in-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/non-delivery-reports-in-exchange-online/fix-error-code-550-5-7-1-in-exchange-online.md)
* Service: **o365-administration**
* Product: **exchange**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@RasTS1 Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

@officedocsbot assign @scanum

**Comment by j0rt3g4** [comment]
Hello @RasTS1 yes, it should be the expected behavior.
But remember, when you disable a user from AD, you're not deleting him... so the user is still present for the Azure AD synchronization.

I mean when you disable a user from local AD (it won't work on Local Exchange server because it's disabled) but this parameter "disable attribute" doesn't synchronize on AAD so Exchange online doesn't know if a user is being disabled or not.

So administratively if you don't want him to receive emails on hybrid you can remove his license on O365 as a part of the "disable process" and it will still receive emails for about 30 days.

**Comment by scanum** [comment]
@RasTS1 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
