### ISSUE TITLE
Exchange 2016 CU10 Information is missing

### ISSUE THREAD

**Issue by Weishaupt** [MicrosoftDocs/OfficeDocs-Exchange#127]
According to https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/prepare-ad-and-domains#how-do-you-know-this-worked it seems like there haven't been any changes?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8acf2480-928a-eb4e-0c9a-8526d97c2713
* Version Independent ID: bcf47ac1-4b6e-e333-1b25-354e4cf88e8a
* Content: [Exchange 2016 Active Directory schema changes](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/active-directory/ad-schema-changes)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/active-directory/ad-schema-changes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/active-directory/ad-schema-changes.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by AndreaBarr** [comment]
@Weishaupt Thank you for this feedback

I agree this should be updated. 

I was able to get this into the backlog for the Exchange team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@Weishaupt, the CU10 information is in the topic: https://docs.microsoft.com/Exchange/plan-and-deploy/prepare-ad-and-domains?view=exchserver-2016#exchange-2016-active-directory-versions. I verified and added the information for CU11. Note that the 3 values might not change from one CU to the next.

Thanks for the feedback.

**Comment by AndreaBarr** [comment]
@chrisda Thank you for grabbing this and getting this answered. 

@Weishaupt I am going to close this issue. If the information Chris gave doesn't resolve the issue please reopen the issue.

**Comment by AndreaBarr** [comment]
@Weishaupt Thank you for the clarification on this. 

@chrisda Do you have an answer for this question?

**Comment by chrisda** [comment]
@Weishaupt, OK, I see what's happening. This issue is related to the topic  [Active Directory schema changes in Exchange Server](https://docs.microsoft.com/Exchange/plan-and-deploy/active-directory/ad-schema-changes?view=exchserver-2016) but your original question (I thought) was about the AD versions section in [Prepare Active Directory and domains for Exchange server](https://docs.microsoft.com/Exchange/plan-and-deploy/prepare-ad-and-domains?view=exchserver-2016).

So, without dragging that other topic into this, your original issue is still valid and unresolved: [Active Directory schema changes in Exchange Server](https://docs.microsoft.com/Exchange/plan-and-deploy/active-directory/ad-schema-changes?view=exchserver-2016) needs to be updated for CU10 and beyond.

 Sorry for the confusion.

**Comment by dariomws306** [comment]
Thanks @Weishaupt and @JeremyTBradshaw . I am working on it, it should be updated soon.

**Comment by dariomws306** [comment]
Hi @Weishaupt and @JeremyTBradshaw , this article was updated to include latest Exchange 2016 CUs. Thank you for your feedbak.
