### ISSUE TITLE
Missing info - need help!

### ISSUE THREAD

**Issue by zimmie67** [MicrosoftDocs/OfficeDocs-Exchange#1461]
This is a great article, but two items left unanswered:
1. is the migration batch job a single move or does it go 95%/5% like a hybrid move? If we wanted to pre-migrate a couple of users as a test, would we be able to "resync" them at cutover?

2. WHat happens to the Outlook client profile that is currently connected to the on-premises Ex13 system? Does the profile follow the mailbox as in a hybrid remote move? Or do  we have to have all users create new profiles?

thanks

**Comment by scanum** [comment]
@zimmie67 Please link the article.Thanks!

**Comment by zimmie67** [comment]
Article link: https://docs.microsoft.com/en-us/Exchange/mailbox-migration/cutover-migration-to-office-365

**Comment by j0rt3g4** [comment]
Hello @zimmie67 

**1. Is the migration batch job a single move or does it go 95%/5% like a hybrid move? If we wanted to pre-migrate a couple of users as a test, would we be able to "resync" them at cutover?**

No, a cutover migration is "all at once", no 95%/5%, it's one way 100%.

**2. What happens to the Outlook client profile that is currently connected to the on-premises Ex13 system? Does the profile follow the mailbox as in a hybrid remote move? Or do we have to have all users create new profiles?**

* Autodiscover URL goes to the "on-premises" side (which has the ability to redirect to Exchange Online.
* Outlook profile needs to be reconnected since the latest connection was on-premise, once migrated the profile needs to be re-done.
