### ISSUE TITLE
What about terminated employees EAS options?

### ISSUE THREAD

**Issue by Canis-Lupis** [MicrosoftDocs/OfficeDocs-Exchange#1470]
There are a couple of items I think need clarification, please.  First off, data wipes would be needed for more than just losing phones.  What about terminated employees? We have a hybrid environment, so when employees are terminated, the first thing we do is delete or disable their AD account.  This syncs up to O365 and deletes the user there.  You can also delete accounts in O365 directly, as many companies do for terminated employees. Therefore, these directions don't work because the terminated employee's mailbox is no longer listed in EAC under recipients.  So, how is data deleted from a terminated employee's phone?

In addition, the article states that, "This procedure will clear all data on the mobile phone, including installed applications, photos, and personal information," but then a few lines later indicates there are two types of wipes; a pre EAS v16.1 and an EAS v16.1+ wipe, with the v16.1+ wipe being an account only wipe and NOT deleting the entire phone.  Later, it then states, " If the client doesn’t support v16.1, the wipe will fail and an error will be given."  So, which is it; will this perform a complete wipe of the phone or will it only delete account information but error out (deleting nothing) if the version is pre 16.1?  We certainly don't want to wipe people's personal phones!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92072b83-beec-a8d5-b5c0-b5900265fbc8
* Version Independent ID: 134ac1f2-0fc9-9598-b89a-72110c16c214
* Content: [Perform a remote wipe on a mobile phone](https://docs.microsoft.com/en-us/exchange/clients/exchange-activesync/remote-wipe?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/clients/exchange-activesync/remote-wipe.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/exchange-activesync/remote-wipe.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Canis-Lupis Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by j0rt3g4** [comment]
@Canis-Lupis 
I think the answers will depend on what kind of licenses you have on O365, in short, if you have or not intune licenses for hybrid.


So Answering your questions:
1. the 1st thing is to check if the user mailbox is "online" or "on-premises".
 If it's on-premises, then you need to do the call of the clean up before disabling it, and in this case on online doesn't matter if he gets removed online
If the user is online, you can use the wipe option using intune.

About 2: 
Actually the only referenced way in article is : **EAS v16.1**. There is no reference in the article related to "pre  EAS v16.1".

**Comment by scanum** [comment]
@Canis-Lupis Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mattpennathe3rd** [comment]
Reopening this one. I will incorporate some edits from another article so that the content from both of these articles align.

**Comment by Canis-Lupis** [comment]
@mattpennathe34rd, thank you!

**Comment by mattpennathe3rd** [comment]
@Canis-Lupis I'll need to take your question in two parts to make sure I'm covering everything!

First, is it possible for these instructions to work by changing the order of the steps you follow on your end to deal with a terminated user? That is, if you (for example) tried to wipe the phone data before disabling their account? Or does this not work? I might be able to address this by pointing out the "gotcha" in the procedure, but if you are saying it is either impossible or just very impractical, then that probably falls under the heading of product feedback. Let me know if there is a way to make this work and I will edit accordingly.

Second, this article is out of date and I am working on a fix. As of EAS 16.1, there are two different ways to wipe data from a device and the behavior differs depending on what wipe you choose and what client is used to connect to Exchange.

If the user is using Outlook, a "Wipe Data" command will delete only their Outlook data. The other type of wipe is "Account Only Remote Wipe Device" (which is confusingly named because it does not wipe the device) and this is not supported at all on Outlook clients; it is redundant because the "Wipe Data" command wipes only Outlook data.

If the user is using a native iOS or Android mail app, "Wipe Data" will indeed wipe their entire device. The "Account Only Remote Wipe Device" command will only wipe the native mail app's Exchange ActiveSync mail and account data.

A fuller explanation for the second part of your question is already written and will be published soon, but I would also like to improve the procedure to address your first questions, also. Please report back when you can.

**Comment by scanum** [comment]
@Canis-Lupis Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by mattpennathe3rd** [comment]
@Canis-Lupis Following up to see if you have further details regarding my questions above. If not, this issue will remain closed. Let me know if I can help.
