### ISSUE TITLE
sample migration fails  Error: The target mailbox doesn't have an SMTP proxy matching ‎'o365.<domain-name>'.

### ISSUE THREAD

**Issue by glloyd82** [MicrosoftDocs/OfficeDocs-Exchange#1526]
following: OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md

I get this issue when attempting to migrate a sample mailbox from gmail to exchange.

Error: TargetDeliveryDomainMismatchPermanentException: Error: The target mailbox doesn't have an SMTP proxy matching ‎'o365.<domain-name>'.

Our office 365 tenant will be syncing with on active directory and we don't run exchange.
How do we fix the above ?

I've followed the guide and create the domain names / aliases on both office 365 and google apps.
Our AADConnect sync tool is set to use email address as an alternative UPN.
email address matches the one on google apps.

Contents of the malibox appear to sync over but it fails at the step mentioned above.

**Comment by mattpennathe3rd** [comment]
@glloyd82 I'd love to help, but this does not appear to be a Docs issue. Please open a support ticket if you're still having trouble with your migration, and if you do find a hole in the documentation, let me know and I'd be glad to fix it up.

**Comment by trueluckdude** [comment]
So I'm not sure if this is still an issue for you but I thought I'd add my experience here for others.

The setup for my client was as follows:
• Client has GSuite for Business accounts
• Client outgrew and wanted to move to M365
• I already had Azure AD syncing enabled and running, for seamless sign-on, for months
• I found the documentation for [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration) and thought "Great, I won't have to export PSTs and manually copy user data, plus I can have the fringe users who are out in the field, continue using their client connections to GSuite until they can come to the office for reconfiguration" - cool.

• I performed the instructions, line-for-line
• Did a sample batch, and everything worked swimmingly - I could see all the user data in their M365 mailbox on outlook.com
• Went to complete the batch, which is supposed to add forwarders, etc, and it eventually failed with the missing proxyAddress error - darn, now what?

I mean, the data was there, but new emails are not going to both places, even with all my public DNS subdomains and entries working.  I started a support ticket with Microsoft, who as extremely helpful and, after two days, was able to come back to me and inform me that the documentation is really geared for Mail Contacts, not for Mailboxes, which is what all my users were provisioned as already...

Let me break to explain that a bit:  Because I had all my on-premise user objects already sync'd and then subsequently given Exchange Online licenses which makes them mailboxes, I would not be able to add a proxyAddress. Had this been a hybrid exchange environment, it would likely have worked, but that was not my case.  I would be able to remove all my synchronized on-premes users from Azure, create corresponding Mail Contacts for GSuite import, but than my Azure AD connect sync would likely fail on those user objects because of the AAD Mail Contacts utilizing the same UPN. You can see now that what we have here is a slightly different environment implementation then the above document is referencing - it's not wrong, seamless sign-on should be embraced for everyone, but not fully compatible with the GSuite migration tool's expectations. 

So back to my dilemma...

What I did have was:
• Verified domains in GSuite and M365/Azure AD
• Working MX records for said domains in public DNS
• Fully sync'd mailboxes on the M365 side

At this point I realized that all I really needed to do was change my primary domain's public DNS MX records over to M365 and manually setup forwarding (with the retain copies in the M365 mailbox option enabled) for each of my clients' users (24 users). These forwarding address would point to user@gsuite.company.com. This was the trick and what the migration tool was trying to do for me but couldn't.  If you have more users than that it may be quite the undertaking, but not terrible and I believe that can be scripted with PowerShell fairly easily. 

Make sure to:
• After verifying your records on the primary domain in the Admin center, modify your TXT SPF record to include both the M365 spf.protection.outlook.com as well as keeping the GSuite include syntax and change to a soft fail (~all, instead of -all). This will allow your users, not yet changed over, to send email from GSuite's SMTP without getting bounced from other mail servers.  You will change this back to the Microsoft recommended SPF record after full cutoff.
• Feel free to use the Complete Migration batch again to sync any missed items throughout the setup process. It will fail but still keeps your data sync'd
• If your users will begin to use their mailbox via Outlook.com, a message appears every time they login, asking if they would like to stop forwarding.  Tell them not to do this unless all their client devices are now pointing to M365. 
• When reconfiguring Outlook for desktop away from the GSuite sync MAPI tool to M365, use the Mail Control Panel applet to create an additional profile for M365, preserving the GSuite existing profile, in case you need to export any missed data or capture your users' autocomplete list for manual import to M365.

I apologize if I'm being flippant with some terms, but I hope this helps others trying to make the move, and I'd be happy to answer more questions for anything I missed in this post.
