### ISSUE TITLE
Update VC++ download links to latest versions

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-Exchange#1554]
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

This update for the Microsoft Visual C++ 2013 Update 5 Redistributable Package is released as a download-only update and isn’t distributed through Windows Update. Redistribution of this update is allowed, subject to the same license terms as granted by the Microsoft Visual Studio 2013 Update 5 release.
https://download.visualstudio.microsoft.com/download/pr/10912041/cee5d6bca2ddbcd039da727bf4acb48a/vcredist_x64.exe

Download the Microsoft Visual C++ Redistributable Packages for Visual Studio 2012 Update 4. This is the latest supported Visual C++ redistributable package for Visual Studio 2012.
https://my.visualstudio.com/Downloads?pid=1452

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e0968e-9590-59a1-83c8-07c218bcf8fd
* Version Independent ID: 42d25a51-bb1a-3d51-75fe-85731236aa04
* Content: [Exchange Server prerequisites, Exchange 2019 system requirements, Exchange 2019 requirements](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/prerequisites?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/prerequisites.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@trudolf-msft Thank you for pointing this out. I've updated the links for 2013, but the link you suggested for 2012 is actually to the same file as already linked in the article. I would prefer not to link to my.visualstudio, as this requires the user to log in and also sign up for a subscription in order to see the download. As such, I've kept the existing link to the Download Center.

The changes should be live in the near future. Thanks again for filing this issue.
