### ISSUE TITLE
Article fails to list which ports need to be open to support hybrid mail flow from Office 365 to customers prem.

### ISSUE THREAD

**Issue by missilelaunchr** [MicrosoftDocs/OfficeDocs-Exchange#1559]
Scenario: Hybrid deployment
Requirement: internal email must flow from users on Office 365 to on-premise exchange.  In order for this to occur ports on the on-prem firewall must be open to allow this mail flow.  This article does not state the IP ranges for these ports.  This article does link to other articles that state which *outbound* ports must be allowed, but this article completely fails to actually serve the goal of providing one the "Hybrid deployment prerequisites".  I've done about 200 Exchange Migrations and about 20 Hybrid deployments, the information I need is standard in this process but seems to be no longer available online via this article or others.  Please address.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ddce84-2ec9-3744-1a3f-20303275affa
* Version Independent ID: 2c5ba0fc-80c4-8de0-61ba-5e73bf558766
* Content: [Hybrid deployment prerequisites](https://docs.microsoft.com/en-us/Exchange/hybrid-deployment-prerequisites#feedback)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by Weishaupt** [comment]
I'm confused, what exactly are you missing? [This section](https://docs.microsoft.com/en-us/Exchange/hybrid-deployment-prerequisites#hybrid-deployment-protocols-ports-and-endpoints)  states the requirements port-wise. Note that modern hybrid doesn't require opening ports externally at all.

**Comment by missilelaunchr** [comment]
Lets get this out of the way, very few outside Microsoft at best, can
understand these articles.  This is why there is countless blogs and forums
essentially re-writing this information, there is a multi-billion dollar
(trillion?) industry of IT consultants performing work for Microsoft
customers much because those customers cannot understand articles like this
one.  My 20 year career and the three MCSE certs I carry are for the
purpose of doing just this.  Lets not make assumptions that these articles
are written in a way one can understand them.  Let's assume they can be
improved.

Part of the challenge is Microsoft is not thinking in terms of IT
networking or thinking in terms of IT.  Saying "Port 25" is not useful
information, no action can be taken with this information.  What IT
requires is a source and destination and direction:
Open port 25 inbound TO your exchange server FROM Microsoft IP address list.

Further, I am working on a hybrid project and had to allow the entire
Exchange Online Protection address range in order to get internal customer
mail to flow from users on Office 365 to users on on-prem Exchange.  So
there is still a requirement to open ports to allow this communication.  On
100% of past Exchange Hybrid projects I've had to open ports to allow
inbound port 25 traffic from Office 365.  This port list is nowhere to be
found it appears, it used to be listed.

Additionally, the entire grid under "Hybrid deployment protocols, ports,
and endpoints" is not understandable or useful.  What is the overall
purpose of this list which appears to be a meaningless list of ports or
services.  This information is not useful unless source, destination and
port are provided.

This sentence is terribly written:
*"Hybrid deployment features and components require certain incoming
protocols, ports and connection endpoints to be accessible to Office 365 in
order to work correctly."*

"Incoming protocols", incoming to what?  This sounds like it is saying this
list of ports and protocols need to be open inbound to Office 365.  Well
Microsoft controls that, you control what inbound protocols, ports and
connection endpoints Office 365 can receive.  But if I basically reverse
the logic of the sentence completely, and re-digest, as is often and
unnecessarily required in Microsoft's articles, I could make this statement
mean that the customer environment must be able to get these ports and
protocols OUTBOUND to office 365.  But again, you don't list the
destination IP addresses or anything so how would one permit this traffic
out.

*"Before configuring your hybrid deployment, verify that your on-premises
network and security configuration can support the features and components
in the table below"*
Impossible to do since you don't list the source or destination (I assume
source is the customer premise).

*"In addition to allowing specific inbound protocols, ports, and endpoints,
computers on your network also need to be able to access the IP addresses,
ports, and URLs listed in Office 365 URLs and IP address ranges."*
This is also written terribly, beyond being difficult to read, it again
does not provide what needs to be open inbound.

If Modern Hybrid is a thing and changes everything, make that clear hear,
on my latest project with the latest hybrid configuration wizard am I using
modern hybrid, how do I know, etc etc.

Happy to hire anyone and pay hourly rate to explain this or surface this
information, explain modern Hybrid and prove out why that somehow solves
this problem and Microsoft no longer needs to provide this information.

Thanks

**Comment by ckssaas** [comment]
+1 for all of this needs to be more thought-out, better documented, and the list of EOP subnets needs to be re-published. We use that every single time a hybrid goes in. It's just a black hole of information right now.

**Comment by ckssaas** [comment]
@Weishaupt EOP IP ranges. That is what is missing. They were taken down months ago per some bonehead decision.

**Comment by danmyhre** [comment]
#needsupdate

**Comment by chrisda** [comment]
@ckssaas, the topic now (as of December) clearly states that the required TCP/IP ports are in the topic: https://docs.microsoft.com/office365/enterprise/urls-and-ip-address-ranges. If there's something missing from that topic, I suggest you open an issue there.

There's no way we're going to even partially repeat any of the information from that topic in this topic; it simply changes too frequently.

**Comment by ckssaas** [comment]
@chrisda The list you have linked to includes 6 subnets for EOP. If you have been doing this for a while you'd know that the previous list included over 30 subnets. When an Exchange Hybrid goes in, the connectors are scoped to the previous list of over 30 subnets. There is a major discrepancy there. We need the complete list in order to open up firewalls prior to running the Hybrid Configuration Wizard. Right now the only way to get the complete list of subnets is to pull it from an existing Hybrid connector (from another customer or another environment) because the complete list has been removed. I have already raised this case on the page you suggested, as have several other knowledgeable cloud partners/architects, and the documentation team still has yet to return the complete list OR confirm that the reduced list is 100% valid. I'm hoping they'll do one or the other. I am speaking on behalf of those of us in the field who actually need that list on a day-to-day basis. The complete list was most likely pulled in order to promote the new modern hybrid model, which most of us can't utilize due to its limitations. Thanks for your concern.

**Comment by dstrome** [comment]
The data in https://docs.microsoft.com/office365/enterprise/urls-and-ip-address-ranges is automatically generated directly from the systems used to control external endpoints we provide for access to the service. 

The authoritative source, from which the topic linked above is generated, can be accessed via the instructions here - https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service.

**Comment by danmyhre** [comment]
@dstrome @chrisda That article states:

> Endpoint data below lists requirements for connectivity from a user’s machine to Office 365. **It does not include network connections from Microsoft into a customer network, sometimes called hybrid or inbound network connections.** See Additional endpoints for more information.

This is the part that is missing.  Please address.  This is needed for both inbound SMTP traffic as well as autodiscover/EWS from Exchange Online to On-Prem in hybrid scenarios.

So, this table:
https://docs.microsoft.com/en-us/Exchange/hybrid-deployment-prerequisites#hybrid-deployment-protocols-ports-and-endpoints

Needs to be updated to include the source.  You can't make firewall rules without a source.  * is not acceptable.

**Comment by missilelaunchr** [comment]
@Weishaupt see this post: https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/722

A Microsoft representative acknowledged the lack of source IP information as a legitimate issue and one that needs to be answered.  Blindly coming to the defense of these ill written articles doesn't help anyone including Microsoft.

**Comment by missilelaunchr** [comment]
> The data in https://docs.microsoft.com/office365/enterprise/urls-and-ip-address-ranges is automatically generated directly from the systems used to control external endpoints we provide for access to the service.
> 
> The authoritative source, from which the topic linked above is generated, can be accessed via the instructions here - https://docs.microsoft.com/en-us/office365/enterprise/office-365-ip-web-service.

@dstrome It's extremely frustrating that you are disregarding this issue and closing the case.  The general culture of assuming these articles are correct and perfect is also extremely frustrating.  We already have the article you linked to and it fails to contain the information we require.  Further, in the link you just shared is the following text _"Endpoint data below lists requirements for connectivity from a user's machine to Office 365. **It does not include network connections from Microsoft into a customer network**, sometimes called hybrid or inbound network connections. See Additional endpoints for more information."_

This article literally says it does _not_ contain the information we're asking for.  It then links to another article which also does not contain the information.

We are asking for the IP addresses for _"network connections from Microsoft into a customer network"_, specifically port 25 to allow mail flow FROM Office 365 TO the customer exchange environment in a Hybrid deployment.

Again:
We need to identify: _"network connections from Microsoft into a customer network"_
The article you linked states: _"It does not include network connections from Microsoft into a customer network"_

The article literally says it does not have the information we are requesting.  The article is talking about **outbound** ports and services that need to be allowed **FROM** the customer site.

Here, someone was gracious enough to admit that this information is missing and it is actually a problem, so perhaps you can reconsider your position on this issue:
https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/722

How this whole thing impacts revenue:
1) A hybrid migration is one of the primary means by which to migrate large organizations to Office 365.  I believe Microsoft recommends hybrid migration for organizations over ~100 seats.
2) Information is missing which is a roadblock in completing #1

This impacts Office 365 revenue by slowing down migration of large customers and making the process more difficult and confusing.  Help us help you.

**Comment by mattpennathe3rd** [comment]
@missilelaunchr @danmyhre @ckssaas I am actively investigating this further to see what can be done. I will report back.

**Comment by mattpennathe3rd** [comment]
@msdmaguire Passing this one to you. It is apparently being worked in parallel in https://github.com/MicrosoftDocs/OfficeDocs-Enterprise/issues/722, so we will need to track.

**Comment by dariomws** [comment]
@missilelaunchr @danmyhre @ckssaas I'm trying to "simplify" this article if you can please let me know your thoughts:
https://github.com/dariomws/OfficeDocs-Exchange/blob/patch-70/Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md#hybrid-deployment-protocols-ports-and-endpoints

Thanks!

**Comment by ckssaas** [comment]
@dariomws Thank you for the follow up and the opportunity to contribute. I have three points of feedback, otherwise I believe the section is very concise and clear:

1. Within the tables and within the boxes outlining port 25 traffic between M365 and Exchange Server: I think it would be ideal to make it more clear in the wording that this is secured TLS encrypted traffic on port 25, as most admins do not associate that port with certificate based auth/secure traffic and that leads to confusion with many of my customers. It would also be helpful to clarify that those routes are intended only for internal mail flow between the organizations and to include citations/elaboration link explaining that smarthosts and filters are not allowed en route between the endpoints. I understand that my second point might be outside the scope of this article.

2. On the second table: I find it confusing that, based on your current description, on-premises Exchange Server endpoints/virtual directories would use Azure AD as an authentication provider. On premises endpoints use AD DS as authentication provider. Autodiscover redirects are the mechanism for changing authentication providers during mail object lookup in a Hybrid Exchange config.

3. It is nice that attention is being paid to this topic, but the actual problem that requires attention is that Microsoft still is not publishing the subnets from which EOP traffic originates. Customers cannot appropriately open their firewalls to secure port 25 traffic from EOP to Exchange frontend without that information. I understand that this appears to be outside the scope of this article, but the problem still needs to be addressed.

Thanks

**Comment by dariomws** [comment]
@ckssaas thank you so much for your feedback. My comments:

1. I think it's an excellent idea to strengthen the information that mail flow uses TLS. I updated the PR. I think we have detailed information about hybrid mail flow in the following articles and I agree that it's out of the scope of this article:
https://docs.microsoft.com/exchange/transport-routing
https://techcommunity.microsoft.com/t5/exchange-team-blog/demystifying-and-troubleshooting-hybrid-mail-flow-when-is-a/ba-p/1420838

2. I think this information is correct, Exchange Online and Exchange on-premises use the Azure Active Directory (AD) authentication Service as the authentication provider. More information:
https://techcommunity.microsoft.com/t5/exchange-team-blog/deep-dive-how-hybrid-authentication-really-works/ba-p/606780

3. I think a few years ago there was an EOP IP addresses article, then all were added to the following article:
https://docs.microsoft.com/microsoft-365/enterprise/urls-and-ip-address-ranges#exchange-online
Currently, these are the endpoints used by EOP:
*.mail.protection.outlook.com
40.92.0.0/15, 40.107.0.0/16, 52.100.0.0/14, 104.47.0.0/17, 2a01:111:f400::/48, 2a01:111:f403::/48

**Comment by ckssaas** [comment]
@dariows Hi Dario, thanks for the response and this is my pleasure.

1. Glad I could be of service.

2. Intention is clear now. I stand by my previous guidance regarding the table row for "Autodiscover". Per other documentation, Exchange Hybrid autodiscover requests must resolve on-prem. On-prem mailbox autodiscover .xml payload requests authenticate to AD while cloud-based mailbox payload requests authenticate to Azure after redirect lookup processes. I think its confusing to suggest autodiscover authenticates against Azure 100% of the time in Hybrid.

Regarding the table row for "Free/busy, MailTips, and message tracking (EWS)": I will defer to those with more experience, but I still find it questionable to suggest Azure auth in this case considering the table is supposed to describe the authentication of requests directed to on-premises virtual directories. In a Hybrid-only context I suppose it makes sense, but there are many different configuration scenarios available to enterprise admins.

3. I reviewed the subnets being scoped to recent 2010 Hybrid "Inbound from O365" receive connectors. It appears the advertised EOP subnets in that article are now in line with connector scope, and I also confirmed mail traffic is originating from within the advertised scope, so that is all good now. I will make the final comment that the linked article states "Endpoint data below lists requirements for connectivity from a **user's machine** to Office 365. It **does not include network connections from Microsoft into a customer network, sometimes called hybrid** " Which could be argued as confusing since the apparent intention of the documentation team is for those EOP subnets to be the same ones scoped to server connectors.

Thanks again for these continued efforts. Best.

**Comment by dariomws** [comment]
@ckssaas thank you so much for your feedback again.

1. Thank you again!

2. I'll try to get more information, I think it's related to "cloud-based mailbox payload requests authenticate to Azure after redirect lookup processes" as you said, but I'm not sure, to be honest.

3. Good to know. I understand your point, this article is focused on client traffic I think. In the same sentence, you have a link to [Additional endpoints not included in the Office 365 IP Address and URL Web service](https://docs.microsoft.com/microsoft-365/enterprise/additional-office365-ip-addresses-and-urls) where you can find more information, for example:
"Mailbox Migration. When mailbox migration is initiated from on-premises Exchange Hybrid to Office 365, Office 365 will connect to your published Exchange Web Services (EWS)/Mailbox Replication Services (MRS) server. If you need the NAT IP addresses used by Exchange Online servers to restrict inbound connections from specific source IP ranges, they are listed in Office 365 URL & IP ranges under the "Exchange Online" service area. Care should be taken to ensure that access to published EWS endpoints like OWA is not impacted by ensuring the MRS proxy resolves to a separate FQDN and public IP address before restricting TCP 443 connections from specific source IP ranges."
Usually, for hybrid, you will focus on mail flow traffic because you'll have Autodiscover, EWS, OWA, etc published to Internet. If you need to restrict these services to Exchange Online endpoints, I think now the information is available in the article and also in the "Additional endpoints not included in the Office 365 IP Address and URL Web service" article.
If you still think that the [Office 365 URLs and IP address ranges](https://docs.microsoft.com/microsoft-365/enterprise/urls-and-ip-address-ranges) needs some improvements, as @chrisda said, we suggest that you open an issue there.

**Comment by dariomws** [comment]
@ckssaas about 2., I think the 3rd row of the table is talking about step 4 in the article [Deep Dive: How Hybrid Authentication Really Works](https://techcommunity.microsoft.com/t5/exchange-team-blog/deep-dive-how-hybrid-authentication-really-works/ba-p/606780) when DAuth is being used.
