### ISSUE TITLE
Memory requirements for Exchange 2019 - hybrid role?

### ISSUE THREAD

**Issue by J-Fedor** [MicrosoftDocs/OfficeDocs-Exchange#1569]
I realize that you have 128GB RAM for mailbox role, but a hybrid server won't have active mailboxes, so I would think the system requirements would be significantly different.  Are there any official recommendations for that?  Didn't see anything mentioned on the page https://docs.microsoft.com/en-us/Exchange/hybrid-deployment-prerequisites - thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c3abd2-dff3-efd8-c046-ac148d95a102
* Version Independent ID: 8a61dd1e-1ba1-1c32-acd2-4e1b25da43a5
* Content: [Exchange Server 2019 system requirements, Exchange 2019 Requirements, Exchange 2019 Memory Requirements, Exchange 2019 Client Compatibility](https://docs.microsoft.com/en-us/Exchange/plan-and-deploy/system-requirements?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/system-requirements.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/system-requirements.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@J-Fedor Because "hybrid" is not really a server role and is more a configuration change in the Exchange Organization, the concept doesn't really apply and thus there are no recommendations aside from using the standard Exchange Sizing guidance documented here and starting with 128GB: https://docs.microsoft.com/en-us/exchange/plan-and-deploy/system-requirements?view=exchserver-2019#hardware-requirements-for-exchange-2019

Every customer environment is different, so there is no way to provide more specific guidance. If you wish to start with less and then monitor performance, you certainly can.

**Comment by J-Fedor** [comment]
While it isn't a role in that sense, it will house no mailboxes and have no persistent client connections (in reality, very few connections at all).  It seems odd that 128GB is recommended for the server operating in this capacity.  Are there plans for an alternate solution for ongoing management of Exchange attributes in a supported fashion and other misc benefits of a hybrid server for Office 365 customers with AADC in place?  Seems to be asking a bit much when this single server is 8-16 times what most of the other servers in a client environment operate with, especially when it essentially is eventually turned into a glorified admin machine.  Thanks.

**Comment by mattpennathe3rd** [comment]
@J-Fedor I'm sorry, but this repo is only a means to raise problems with the documentation and I am not able to provide product support or speak to future plans; I would love to help, but I am only a Technical Writer. For questions like this, you will need to open a Support ticket.
