### ISSUE TITLE
article last updated date is incorrect

### ISSUE THREAD

**Issue by Mike-Crowley** [MicrosoftDocs/OfficeDocs-Exchange#1587]
This page is meant to serve as a place for admins to check out the latest versions of Exchange 2013. CU23 was released in June 2019, for example. This page however says that it was last updated "03/19/2018". Does this not automatically update when the page's content is changed? if so, its broken. If not, I guess it should be manually updated. every time a new update is available. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a97114e1-a2f9-058c-770c-ca2cf297972a
* Version Independent ID: 28933a4c-6af5-7045-6f20-d0e78a974055
* Content: [Updates for Exchange 2013: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/updates-for-exchange-2013-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/updates-for-exchange-2013-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/updates-for-exchange-2013-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mariankral** [comment]
@chrisda
When will the next release be - Exchange Server 2013 CU24?

**Comment by mariankral** [comment]
And also Update Rollup 30 for Exchange Server 2010 SP3 ?

**Comment by chrisda** [comment]
@Mike-Crowley, the last modified date problem is related to the migration of content from TechNet last year. That value can be controlled by a metadata tag in the topic with a static date that whomever updates the topic must remember to update. Not exactly sustainable, and all topics that came over from TechNet had that tag.

We've since (literally two days ago) removed that metadata tag from all Exchange content globally so that any update to the topic automatically sets the last modified date. So problem solved.

@mariankral, Exchange 2010 and 2013 are no longer on the quarterly release cycle, so only something like a security issue would cause a new CU or RU to be released. Future CUs for 2013 are more likely than future RUs for 2010, because 2010 is very close to its end of support date.

Thanks for the feedback.
