### ISSUE TITLE
Seriously we are unable to remove the Exchange server due to simple problem of managing some attributes?

### ISSUE THREAD

**Issue by sw-sw-sw-sw** [MicrosoftDocs/OfficeDocs-Exchange#1595]
"When directory synchronization is enabled for a tenant and a user is synchronized from on-premises, most of the attributes cannot be managed from Exchange Online and must be managed from on-premises."

Can this article provide a list of the attributes that must be managed using on-premise Exchange (EAC), vs EAC in O365 vs EXOShell?

It's not a viable solution to tell clients who've 100% migrated to Exchange Online but still have an on-premise domain that they must continue to patch and manage their exchange server, especially since 2008r2 is coming out of patch support and the cost of exchange and server licenses. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6eb1f9b-27f6-4d93-5a97-ad3f8b6ed27d
* Version Independent ID: f248ffa0-1bc3-be8f-055a-1c941e3ad234
* Content: [How and when to decommission your on-premises Exchange servers in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange#feedback)
* Content Source: [Exchange/ExchangeHybrid/decommission-on-premises-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/decommission-on-premises-exchange.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by RescueWhale** [comment]
IKR, the most dumbass decision ever. They have had years to fix and still haven't, so I'm assuming they never will

**Comment by amolpawar297** [comment]
They should have fix this by now.. i have migrated all users to cloud and now i have to keep one exchange server running just for management.. Not good Idea. i dont know how to explain this to client.

**Comment by atguilmette** [comment]
It's largely designed similarly to how Exchange resource forest configurations work--you have to manage properties of the mailbox where the mailbox is and properties of the identity where the identity is.  Features and properties that are set on the Active Directory user (name, description, username, manager etc) are managed at the user object level.  Things that are solely related to the Exchange mailbox operation (operations performed by Set-Mailbox, Set-MailboxFolderPermission, user safe sender lists or delegates, etc) are managed on the mailbox object itself.

**Comment by Krytical13** [comment]
> It's largely designed similarly to how Exchange resource forest configurations work--you have to manage properties of the mailbox where the mailbox is and properties of the identity where the identity is. Features and properties that are set on the Active Directory user (name, description, username, manager etc) are managed at the user object level. Things that are solely related to the Exchange mailbox operation (operations performed by Set-Mailbox, Set-MailboxFolderPermission, user safe sender lists or delegates, etc) are managed on the mailbox object itself.

The limitation makes no logical sense.

Think about it, Azure AD Connect.
This tool's purpose is to synchronize everything on premise with Azure AD. (What O365 reads from)
We have access to both;
The user object, in Azure Portal and the Mailbox object, in the O365 Portal.
IE:  if we create an Azure AD only user, we can modify any attributes.
If we create an O365 only user, we can modify any attributes.

Now however, we create that same user On-premise and sync using Azure AD Connect.
Now for this user, two different cloud portals are suddenly useless for modifying the exact same attributes that we are able to modify on the exact same type of objects if we create them in the cloud without DirSync.

So to me, the limitation makes no logical sense.
Especially given the amount of time this has been an issue, and how much Money MS is making off of these cloud services.

So the reality is, it's just not a Priority like many things users *want* to be a priority.

**Comment by SLGPA** [comment]
Critical attributes you requested a list of:
msExchMailboxGUID
msDsConsistencyGUID
proxyAddresses
E-mail address policies (Yes, this is not an attribute, but Exchange ensures uniqueness and the consistency of proxyAddresses)
legacyExchangeDN (and X500 addresses in the proxyAddresses as well)

**Comment by skrubbeltrang** [comment]
While we wait, have a look at this: https://www.easy365manager.com/
It will let you manage user's mail attributes, Exchange Online mailbox attributes and Office 365 licenses inside good old AD Users & Computers :-)

**Comment by Krytical13** [comment]
> Critical attributes you requested a list of:
> msExchMailboxGUID
> msDsConsistencyGUID
> proxyAddresses
> E-mail address policies (Yes, this is not an attribute, but Exchange ensures uniqueness and the consistency of proxyAddresses)
> legacyExchangeDN (and X500 addresses in the proxyAddresses as well)

@SLGPA 
Thank you for that, however by saying:
"Critical attributes"
You make it clear that there are more attributes, and that someone else has decided which of the attributes are critical and which are not.

This entire problem at hand is: Where can we manage the things we NEED to manage?
Most of those those attributes you listed, should never be modified unless there is an issue.
In those one-off situations, editing using ADUC/ADSI Edit/PowerShell etc. is fine, so this is not the problem.

The problem lies with the attributes you haven't mentioned.
For example:
We are unable to add/remove members of a distribution list in the Exchange Online portal/ECP.
This is MUCH more critical than being able to edit the msExchMailbboxGUID which shouldn't typically be modified anyway.

So can someone provide a list of attributes that people would actually use on a day to day basis?

**Comment by srautwar** [comment]
Microsoft Exchange Team, Any update on this? This is a MUST have item for the last several years. It is painful the manage the on-perm Exchange Server just to manage few attributes. Please come up with a solution to address this limitation.

**Comment by schodosa** [comment]
Also in need of an update. Planning DNS changes tonight and had no intention of leaving an on-prem Exchange Server running.

**Comment by Krytical13** [comment]
M$ is about making money...
So what do they do?
Save money by having less developers, and less expensive ones 
(See quality of windows 10 updates, and removal of matured features from mature enterprise software due only to the inability to maintain the code for confirmation of this)

Save money by getting the community to do their documentation, rather than spend a bunch of money on employees to document fully and properly like a normal company...

Save money and also make more money by having those previously mentioned developers, purposely leave features missing for long periods of time, so 3rd party sellers can come fill that need and also pay MS to be gold partner etc.
For example:
Signatures and Stationary
GAL Syncing to users Outlook
Managing the properties of objects
Searching for and deleting emails in bulk


I can't think of more right now..  but M$ isn't stupid... they know exactly what they are doing.

**Comment by mattpennathe3rd** [comment]
@sw-sw-sw-sw @RescueWhale @amolpawar297 @atguilmette @Krytical13 @srautwar @schodosa 

I checked thoroughly into this and as of right now, there is no solution. You do have access to a free license (the "hybrid key") for the remaining hybrid server via the Hybrid Configuration Wizard, so the remaining server should not incur further software cost.

I'm sorry that I'm not able to help further; I only work on the documentation. I do suggest that you keep an eye on the Exchange blogs for further news.
