### ISSUE TITLE
invalid powershell pre-reqs specified

### ISSUE THREAD

**Issue by hihoman1980** [MicrosoftDocs/OfficeDocs-Exchange#162]
the package AS-HTTP-Activation is no longer needed nor available since windows2016. The powershell prereqs command therefore will lead to an error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e9e0968e-9590-59a1-83c8-07c218bcf8fd
* Version Independent ID: 42d25a51-bb1a-3d51-75fe-85731236aa04
* Content: [Exchange Server prerequisites](https://docs.microsoft.com/en-us/exchange/plan-and-deploy/prerequisites?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/plan-and-deploy/prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/plan-and-deploy/prerequisites.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@hihoman1980 Thank you for this information

I will make sure the Exchange team gets this so that we can get this article updated. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@hihoman1980, if you're talking about Exchange 2019, I've removed AS-HTTP-Activation from the Exchange 2019/Windows 2019 code blocks. There was also a duplicate Web-Mgmt-Console value in every code block, so I removed that, too.

Thanks for the feedback.
