### ISSUE TITLE
Should be semicolons not commas

### ISSUE THREAD

**Issue by CaseGuide** [MicrosoftDocs/OfficeDocs-Exchange#1625]
The Powershell instructions work but if using the Exchange Admin Center separating with a comma gives an invalid string. Use a semicolon instead. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e64e56f9-fbf4-f072-637b-5fa8e827a399
* Version Independent ID: 32a37550-af95-a0ce-2941-ff9ce7ba9150
* Content: [Create an organization relationship in Exchange Online](https://docs.microsoft.com/en-us/exchange/sharing/organization-relationships/create-an-organization-relationship#feedback)
* Content Source: [Exchange/ExchangeOnline/sharing/organization-relationships/create-an-organization-relationship.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/sharing/organization-relationships/create-an-organization-relationship.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by dariomws306** [comment]
Hi @CaseGuide, thank you for your feedback.

Same issue for me with semicolon:
![image](https://user-images.githubusercontent.com/33589238/74854392-09fe3380-531e-11ea-851c-b8d00890e9c5.png)

Could you kindly share a screenshot?

**Comment by mattpennathe3rd** [comment]
@CaseGuide Just following up. Can you clarify your problem so we can verify if the article is wrong?

**Comment by CaseGuide** [comment]
I cannot recall the details of this minor technical issue from 4+ months ago. From my vague recollection the tuteotial for the Exchange Admin Center didn’t work if you separated domains with a semicolon. Using a comma did. To verify, follow the tutorial using the EAC.

**Comment by dariomws** [comment]
Hi @mattpennathe3rd,

The issue is on step 5: "If you need to enter more than one domain, separate the domain names with a comma. For example, contoso.com, service.contoso.com."

Use a comma to separate the domain names is not working:
![image](https://user-images.githubusercontent.com/33589238/79044616-8275c800-7bdc-11ea-9726-4ad8b514005b.png)

Semicolon for me neither:
![image](https://user-images.githubusercontent.com/33589238/79044637-94f00180-7bdc-11ea-8b55-d555650fb0bb.png)
