### ISSUE TITLE
Retain my Exchange 2007 Server

### ISSUE THREAD

**Issue by ducatikiller** [MicrosoftDocs/OfficeDocs-Exchange#1685]
This is quite unbelievable.  My customer will be stuck with an aging, no longer supported Exchange 2007 server running on Windows Server 2003 because we want the password sync of a hybrid-AD and use AD Connect?  I'm glad everyone is proud of the ease of a hybrid exchange wizard (kudos) this seems to be a gaping wound.  Perhaps my ignorance of the underpinnings allow me to say that with ease but at the end of the day, I wish this was more of a bug than a feature.   This forces a complete rethink of the plan to migrate into O365 and Azure.  AWS and a complete wash of authentication integration is now a possibility. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6eb1f9b-27f6-4d93-5a97-ad3f8b6ed27d
* Version Independent ID: f248ffa0-1bc3-be8f-055a-1c941e3ad234
* Content: [How and when to decommission your on-premises Exchange servers in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange)
* Content Source: [Exchange/ExchangeHybrid/decommission-on-premises-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/decommission-on-premises-exchange.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@ducatikiller I'm sorry, but this does not seem to be a documentation issue. This repo is only for feedback on the documentation, as I'm unable to offer Support here or answer deployment questions. (I'm only a Technical Writer.) My advice is to open a support ticket. They will be able to advise you on what's best in your environment.

If it turns out there's a gap in this article, please open a new issue and I'd be glad to help with that.
