### ISSUE TITLE
Wrong information

### ISSUE THREAD

**Issue by MDanihy** [MicrosoftDocs/OfficeDocs-Exchange#1690]
You cannot apply an EOP License on an account. 

"Licensing: SMTP relay doesn't use a specific Office 365 mailbox to send email. This is why it's important that only licensed users send email from devices or applications configured for SMTP relay. If you have senders using devices or LOB applications who don't have an Office 365 mailbox license, obtain and assign an Exchange Online Protection license to each unlicensed sender. This is the least expensive license that allows you to send email via Office 365."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@MDanihy Thank you for opening this issue. I'll have to investigate further, but will report back with an update.

**Comment by msbemba** [comment]
@MDanihy  Thank you for your feedback. The document refers to a Standalone EOP license (https://products.office.com/en-us/exchange/exchange-email-security-spam-protection).

Hope this helps!

Thanks
Sri

**Comment by mattpennathe3rd** [comment]
@msbemba Thanks for that. Do you think this article can be clarified in any way, or is it good as it stands? If you think it's good, you are welcome to close this issue.

**Comment by omeriniit** [comment]
I got trial version from https://products.office.com/en-us/exchange/exchange-email-security-spam-protection
Now I have 25 EOP licenses and cannot assign them to anyone because "Exchange Online Protection (These licenses do not need to be individually assigned)." I can make contacts and connector but there's no difference if I have 1 license or 25 licenses. But that is true that EOP - This is the least expensive license that allows you to send email via Office 365.

Also it does not make sense if one paragraph says that sender does not need to be associated with an actual mailbox but another paraggraph says that "If you have senders using devices or LOB applications who don't have an Office 365 mailbox license, obtain and assign an Exchange Online Protection license to each unlicensed sender."

"Your device or application can send email using any address (including ones that can't receive mail), as long as the address uses one of your domains. The email address doesn't need to be associated with an actual mailbox. For example, if your domain is contoso.com, you could send from an address like do_not_reply@contoso.com."

Please clarify how many licenses are needed and how can they be assigned to user accounts.
