### ISSUE TITLE
400 Bad Request for forwardingAddress

### ISSUE THREAD

**Issue by IanBarnesZa** [MicrosoftDocs/OfficeDocs-Exchange#1696]
Hi,

When running a migration from GSuite to O365, it appears that all emails get migrated, but the migration fails with the following error:

Error: `TooManyTransientFailureRetriesPermanentException/BadRequestWebTransientException/WebException: Error: The job encountered too many transient failures ‎(88)‎ and is quitting. The most common failure is BadRequestWebTransientException/WebException with the hit count 60. --> The web server responded with a 400 Bad Request error. Uri: https://www.googleapis.com/gmail/v1/users/user@domain.com/settings/forwardingAddresses --> The remote server returned an error: ‎(400)‎ Bad Request.`

Not sure why this would be? I am not setting up the subdomains as my mail accounts have been created , mx records updated and are being used on the O365 instance, I am just bringing in historical mails to close off the account.

Thanks
Ian

**Comment by RobXYZ** [comment]
I had the same error and discovered it was because I had the "target delivery domain" setting in the migration set to the main domain instead of a temporary o365 subdomain. I assume the Google API is complaining because it is being asked to forward emails back to the same mailbox.

If everything is migrating fine and your MX records are pointing at O365 there is not really any reason to add the forwarding address to Gmail anyway so you can probably safely ignore this error.

**Comment by IanBarnesZa** [comment]
Thanks RobXYZ - makes sense what you're saying. 
I've moved on already, just thought perahps this should get an FAQ or something at least.

**Comment by mattpennathe3rd** [comment]
@IanBarnesZa I'm sorry, but this sounds like a configuration issue rather than a docs problem, so please open a support ticket if you still need assistance. This repo is only for providing feedback on documentation, so I am unable to answer support questions here. (I am only a Technical Writer.)

**Comment by IanBarnesZa** [comment]
Yes, It definitely is a configuration issue, not debating that, but since you know what causes it - perhaps it could feature in an FAQ of error messages and what the cause is. Will close this anyway...

**Comment by RobXYZ** [comment]
I opened a support ticket that was running for almost 3 weeks with two engineers and no resolution. The engineers did not know the cause of the error and I eventually stumbled across the solution myself. The problem is the error does not give much information so it would be useful if this was documented somewhere.

**Comment by VLG17** [comment]
@IanBarnesZa @RobXYZ @mattpennathe3rd would [this](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration) be a good candidate to add a note about this error to? Maybe at the end of the article under "Finalizing your migration".

If yes, could you please link it to this issue so i can do that?

**Comment by RobXYZ** [comment]
That would definitely be the best place to document it.

To link it would I need to create a new issue related to that page and link to this issue?

**Comment by mattpennathe3rd** [comment]
@RobXYZ @VLG17 I'll follow up with the engineers and see what we can document on the migration article.

**Comment by scanum** [comment]
@RobXYZ  Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
