### ISSUE TITLE
How do you then remove the expired certificate?

### ISSUE THREAD

**Issue by jkubikng** [MicrosoftDocs/OfficeDocs-Exchange#1711]
You can't just delete the certificate that expired as you do with other certificates you replace in Exchange.  It is something we do want to remove and clean up.  We don't want to just leave it there.  Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b3694c-16ed-97fb-1423-16d950922396
* Version Independent ID: fd8bf16d-7ed7-c0f9-3157-e11fc0653829
* Content: [Renew the federation certificate: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/renew-the-federation-certificate-exchange-2013-help#feedback)
* Content Source: [Exchange/ExchangeServer2013/renew-the-federation-certificate-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/renew-the-federation-certificate-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@jkubikng Thanks for submitting this. I don't have an immediate answer for this, but I will investigate and see if there's a way to clarify this in the article.

**Comment by JeremyTBradshaw** [comment]
@jkubikng I found this https://social.technet.microsoft.com/Forums/en-US/f5349498-df20-4cea-a565-bd544ed56b0a/how-to-remove-previous-federation-gateway-certificate?forum=exchangesvradmin which you may have as well.  They say there that they did it via the MMC (certlm.msc in 2012 R2 and newer).  Seems like a stinky approach, but just FYI for now.

**Comment by JeremyTBradshaw** [comment]
Oh, and don't miss the step after in ADSI Edit to remove the dead cert's thumbprint from the Federation Trust (again stinky stuff here).
"I did wind up getting this fixed- I had to use ADSIEdit to copy the thumbprint of the current cert into the OrgPrevPrivCertificate value."

**Comment by mattpennathe3rd** [comment]
@jkubikng @JeremyTBradshaw After checking, I'm sorry to say there is no officially supported way of doing this at this time. We're not comfortable recommending that customers start deleting things using ADSI Edit, so we're not going to document that here; the ramifications aren't clear and it opens the door to making unintentional errors.

I recommend that you open a support ticket because they'll be able to help you further. (I am not a support person and the support team does not monitor this repo; I only work on the documentation.) I'll also point this out to Engineering, but I can't guarantee anything beyond that and I don't expect to have any further updates, so I will close this issue now.

**Comment by JeremyTBradshaw** [comment]
Thanks @mattpennathe3rd , and I only meant to offer those solutions to @jkubikng , but not actually to have that process added to the article here.  Agreed, advising Adsi edits here would attract a lot of mayhem haha.

**Comment by jkubikng** [comment]
@mattpennathe3rd Thank you for looking into this.  It's interesting Microsoft has these certificates then no way to cleanly remove them after they expire.
