### ISSUE TITLE
Native Microsoft Sync Clarification

### ISSUE THREAD

**Issue by mcastorina08** [MicrosoftDocs/OfficeDocs-Exchange#1717]
The specific protocol is not mentioned. Does Outlook for IOS/Android use MAPI over HTTP?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b221cd8e-e6d1-e383-65a2-11f7241de966
* Version Independent ID: cf978d97-c1e6-f0b7-7407-4f70d2284d17
* Content: [Outlook for iOS and Android in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android#feedback)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@mcastorina08 Thanks for filing this issue. I will have to investigate this, but will report back soon on whether we can clarify this a bit.

**Comment by GiantCrocodile** [comment]
In same context of the original request: I would like to see clarification if HTTP or HTTPS is used and if HTTPS, how strong the encryption is mattpennathe3rd

**Comment by smithre4** [comment]
The HTTP connection between Outlook mobile and Exchange Online is secured with TLS 1.2.

**Comment by mattpennathe3rd** [comment]
@mcastorina08 The protocol used is encompassed in the native Microsoft sync technology. It is not MAPI over HTTP. I've tried to clarify this a bit in the article and I hope this helps.

@GiantCrocodile In line with the comment above, I've clarified in the article that we use TLS 1.2 over HTTPS.

The updated version of the article should be published in the near future. Thanks very much for asking these questions so that I can improve the docs.
