### ISSUE TITLE
Does this migration method work in GCC High environments?

### ISSUE THREAD

**Issue by hilljw** [MicrosoftDocs/OfficeDocs-Exchange#1727]
If so, are there special configurations required to make it work? 
If not, what are the allowed options for migrating email to O365 GCC High?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75c68b82-8feb-80fd-2e70-49199991dcd7
* Version Independent ID: 875fbcea-7a00-ca24-2edb-20bbee3744a8
* Content: [Migrate consumer G Suite mailboxes to Office 365](https://docs.microsoft.com/en-us/Exchange/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes#feedback)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/migrating-imap-mailboxes/migrate-g-suite-mailboxes.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by lindspea** [comment]
@mattpennathe3rd

**Comment by mattpennathe3rd** [comment]
I'll see if I can dig up an answer to this one. I will report back.

**Comment by mattpennathe3rd** [comment]
@hilljw I checked with our migration team and this is currently not possible. Because of the way in which GCC High (and similar) environments are locked down, they do not have access to G Suite, so the migration cannot work.

Unfortunately, there is no timeline for when (or if) this might be supported.

Please let me know if I can be of further help with docs issues.
