### ISSUE TITLE
MFA for SMTP Relay

### ISSUE THREAD

**Issue by bmshahrier** [MicrosoftDocs/OfficeDocs-Exchange#1741]
Option 1 don't work if MFA enabled on account. If this information could be mention in this article, it would same time for administrators and Microsoft support. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Office 365](https://docs.microsoft.com/en-us/Exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3#feedback)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-office-3.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@bmshahrier  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by John-D1** [comment]
We did not have problems using App Passwords with MFA until we enabled Azure AD security defaults last week.  Once you enable the Azure AD security defaults it turns off App Passwords. 

REF: ** App passwords are only available in per-user MFA with legacy authentication scenarios only if enabled by administrators.

https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/concept-fundamentals-mfa-get-started

**Comment by bacon1986** [comment]
I've spent about a week or more fighting this one trying to work out why I can't get SMTP to work from any device using Option 1 no matter what I do with passwords and app passwords and why MFA is being required for an account where MFA appears not to be enabled. Can you please update this document to make it clear that "Security Defaults" are now enabled by automatically for new tenants and stop this process from working? Thanks.

**Comment by John-D1** [comment]
As of this message, here's where I'm at with Microsoft.

Basically once security defaults are enabled on an Office 365 account you must pay for Azure AD premium in order to allow for trusted IP ranges.

You can access both features below with one license, which is assigned to the Global Administrator account, to manage Conditional access policy and trusted IP features...

Once you have Azure AD Premium P1 or better, there are two areas that will then apply:

1) Trusted IPs -- From the “Azure Active Directory > Security > Conditional Access” area referenced in this document:
https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-mfasettings#trusted-ips

2) MFA service settings -- From the “Azure Active Directory > Security > MFA” window referenced in this document:
https://docs.microsoft.com/en-us/azure/active-directory/authentication/howto-mfa-mfasettings#mfa-service-settings

**Comment by blazncaczn** [comment]
@bacon1986 You can find "Security Defaults" in "Azure Active Directory" panel, then select "Properties". You'll see an option for "Manage Security Defaults" at the bottom of the screen for the Directory Properties.

**Comment by paulypoteat** [comment]
I've enabled security defaults (which broke things).  Based on @John-D1 I've purchased Azure AD Premium P1 and added the public IP as a trusted IP in Azure (and also manually listed it in the Office 365 MFA trusted IP section). That said, option 1 still isn't working.  ISP is blocking port 25 so option 2 never worked.

**Comment by John-D1** [comment]
paulypoteat, I would open a case with Microsoft to review your exact configuration.  Here are some ideas that come to mind, Did you assign the P1 license to the global administrator or the user that needs to authenticate?  My understanding was that the license needed assigned to the global administrator however you may want to try assigning it specifically to the user.  Also, it's possible that some of the Microsoft changes can take a while to apply or could get hung up requiring a support case to review.  Regarding the "Trusted IPs" and "MFA service settings", perhaps try adding your Public IP block and not just your Public Static IP to the allowed range.  IE /30 /29 /28, etc...  Lastly, after your changes, did you create a new app password for access?

**Comment by blazncaczn** [comment]
@paulypoteat When you review your sign in attempts on Azure AD for the account that's sending email, what are you seeing in those logs? It might tell you exactly what is going on. If you have a Premium Azure AD license you can setup a conditional access policy and exclude the user account for requiring MFA with Exchange Online and that should resolve the problem, I'd also recommend putting in the Trusted Location to match on that policy.

**Comment by paulypoteat** [comment]
I added AADP1 to a global admin (not the end user) and whitelisted the end user's home IP.  I believe this worked because browser logins for that user (from that location) no longer trigger MFA even when incognito.  I think the issues is this is more than just MFA.  Security Defaults enables MFA and also disables SMTP-Auth.  Whitelisting the home IP doesn't help get the SMTP portion working (I don't think).  John-D1, I was using the users password, not an app password.  I just tried to create a new app password and that didn't work either.  Everything I'm doing is through the Brother Scanner Web Interface which doesn't give you much to work with in terms of logs.

**Comment by mattpennathe3rd** [comment]
@bmshahrier Thanks for pointing this out. There was a note about this buried late within the Option 1 section, but it was subtle. I have updated the article in several places so that this is more obvious. The updated article will be published in the near future. Thank you very much for opening this issue and helping us improve the documentation.

**Comment by John-D1** [comment]
@paulypoteat , that's not the case.  We were using the app password and it was working fine until the Security Defaults were enabled.  Are you saying that you were unable to "Enable SMTP AUTH for specific mailboxes"?

With what you're saying, Microsoft support was in error regarding their information and licensing isn't needed at all.

**Comment by paulypoteat** [comment]
I'm suggesting that the idea of an app password is meant to work around MFA.  Another work around is IP white-list.  Separately, when you enable Security Defaults MS forces MFA AND disables legacy (like Send Auth for Multi Function Printers).  I don't think App Passwords or IP White-list will help our situation - where we've enabled Security Defaults but our printers don't support modern authentication.  I think that's a pretty succinct description.  I'd love if someone from MS can confirm that so we can just move onto finding a different approach (like using the ISP's provided credentials <sigh>)

**Comment by John-D1** [comment]
@paulypoteat , we have a lot of customers with legacy devices such as your printer.  For some of the customers, we ended up installing a local free SMTP server such as mailenable or hmail on one of their clients which could do all of the heavy lifting however it presents an issue with sending to 3rd party domains.  The preferred method that we were using prior to the 'security defaults' enforcement was an app password.  The app password worked great and some customers would even pay for a donotreply box or similar.  It also avoided the problem with them changing their main account password.  Now that it's not working, Microsoft Support indicated that buying an AADP1 or better was required for it to work but based on your reply sounds iffy at best.  Modern Authentication wasn't required for the app password before so this should have worked... however I did miss the documentation about "Enable SMTP AUTH for specific mailboxes".  Did you try that and wait up to 48hrs? REF https://docs.microsoft.com/en-us/Exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission

**Comment by paulypoteat** [comment]
@John-D1 For clarification we are/were in the same boat.  We were using App Password (to get around the MFA requirement that we self imposed).  When we enabled Security Defaults it stopped working.  I conflated issues and thought that AAD Premium1 (and setting an IP whitelist) would help.  All that did was get us past MFA.  Security Faults, I believe, kills SMTP Auth ONTOP of forcing MFA so there are 2 different hurdles.  I can see the documentation is now updated to say Option 1 (SMTP Auth Submission) is not compatible with Security Defaults, so at least now its definitive.  Problem for us is Option 2 and Option 3 also don't work because ISP restricts port 25.  OUr work around is to use SMTP Auth to the ISP's SMTP server and bypass MS entirely.  It's not eloquent but unless they make Option 4 we're stuck.

**Comment by John-D1** [comment]
@paulypoteat , I totally agree, Option 2 and 3 are not realistic...  any chance you could open a support case with Microsoft to get a final answer regarding this?  ...and depending on that final answer the authenticated client submission docs may also need updated.

**Comment by paulypoteat** [comment]
@John-D1 I believe Microsoft has updated to my <cough><cough> satisfaction.  It now reads 
"Note: This option is not compatible with Microsoft Security Defaults or multi-factor authentication (MFA). If your environment uses Microsoft Security Defaults or MFA, we recommend using Option 2 or 3 below."

That's everything I needed to know.  I don't believe opening a ticket is going to improve my (our) situation.  This feels like a https://office365.uservoice.com/ move now.

**Comment by dbacher** [comment]
Try port 587:
https://kinsta.com/blog/smtp-port/#:~:text=Port%20587%20is%20the%20default%20port%20for%20SMTP,your%20host%20blocking%20port%20587%20for%20some%20reason%29.

> If you’re configuring your WordPress site or email client to send emails via SMTP (submission), you’ll almost always want to use port 587. Again, this is the default SMTP port for submission and it supports secure transmission via TLS.

O365 supports it, your ISP likely doesn't block it by default.
