### ISSUE TITLE
NLB with DAG

### ISSUE THREAD

**Issue by ericreiss** [MicrosoftDocs/OfficeDocs-Exchange#1797]
Under the section "Load balancing options in Exchange Server" it says that "Be aware that DAGs use Microsoft Clustering Services. These services can't be enabled on the same server as Windows Network Load Balancing (NLB). Accordingly, Windows NLB is not an option when using DAGs. "  Are you saying you can't use NLB on a different Windows Server/VM  that is separate from the DAGs?

Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba4bfd3e-15c4-d7ab-f4c8-579352581bb3
* Version Independent ID: 6178892e-ec14-d9de-cd17-aeee5302994b
* Content: [Load balancing in Exchange Server](https://docs.microsoft.com/en-us/exchange/architecture/client-access/load-balancing?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/architecture/client-access/load-balancing.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/architecture/client-access/load-balancing.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by VLG17** [comment]
@ericreiss You can leverage NLB on a different Windows Server / VM which is not part of a DAG structure. 

The article states that NLB cannot be installed on a server that is part of a failover cluster (DAG) as the two clustering technologies are not compatible.

**Comment by dariomws** [comment]
@ericreiss Thank you for submitting feedback and contributing to the docs.

Windows Failover Clustering and Windows Network Load Balancing (NLB) are not supported in the same server. You can have them in separate servers.
Since the only server role in Exchange 2016 or 2019 is the Mailbox role, you cannot use NLB in a high availability deployment.

The latest version of Exchange where you can use NLB is Exchange 2013. More information:
https://docs.microsoft.com/exchange/load-balancing-exchange-2013-help#windows-network-load-balancing

**Comment by scanum** [comment]
@ericreiss Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
