### ISSUE TITLE
discrepancy 

### ISSUE THREAD

**Issue by copenhaus** [MicrosoftDocs/OfficeDocs-Exchange#1805]
there's a discrepancy on the version number with this page:  https://www.microsoft.com/en-us/download/details.aspx?id=100908

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aaf984bf-df1c-bcd5-6475-54b9ef24fe74
* Version Independent ID: 00547ab9-7b3b-f6b0-fa7f-429f5e2bea56
* Content: [Exchange Server build numbers and release dates](https://docs.microsoft.com/en-us/exchange/new-features/build-numbers-and-release-dates?view=exchserver-2019#feedback)
* Content Source: [Exchange/ExchangeServer/new-features/build-numbers-and-release-dates.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/new-features/build-numbers-and-release-dates.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@copenhaus Thank you for pointing this out, but which version number(s) will need correction?

**Comment by copenhaus** [comment]
the latest version number (as of today and according to the page I linked) is 15.01.1913.007

**Comment by mattpennathe3rd** [comment]
@copenhaus I see what you're saying. What you linked to is a security update for CU15, which has a later version number than CU15 itself; the version number for CU15 itself (which is what is documented on this page) is correct, I believe. We only document release version numbers here because it would be very difficult to maintain the latest release version numbers after every minor update.

You can find the download for CU15 here and its version number matches the documentation: https://www.microsoft.com/en-us/download/details.aspx?id=100780

Please comment back if I have misunderstood, but I will close this issue for now. I appreciate your opening the issue.
