### ISSUE TITLE
Internal links in this doc do not work.

### ISSUE THREAD

**Issue by notanic** [MicrosoftDocs/OfficeDocs-Exchange#187]
Hi,
Internal links are broken:

•General
•Delegates
•Booking Options
•Contact Information
•Email Address
•MailTip

The links have '.md' on the end, whereas the target does not.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bbfe623f-85a6-d71f-f3df-46500fffb2e0
* Version Independent ID: e91cc9e4-3fac-4839-c749-f0c521fae33c
* Content: [Manage equipment mailboxes](https://docs.microsoft.com/en-us/exchange/recipients/equipment-mailboxes?view=exchserver-2019#Delegates.md)
* Content Source: [Exchange/ExchangeServer/recipients/equipment-mailboxes.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/recipients/equipment-mailboxes.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by AndreaBarr** [comment]
@notanic Thank you for this feedback

I will get this over to the Exchange team so that we can investigate these broken links. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by chrisda** [comment]
@notanic, I fixed them. Thanks for the feedback.
