### ISSUE TITLE
Are Mail Flow Rule Actions Strictly Ordered?

### ISSUE THREAD

**Issue by philkloose** [MicrosoftDocs/OfficeDocs-Exchange#1870]
Are mail flow rule actions always executed in the order that they appear?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81c1119-165b-f408-698c-1092a781ba63
* Version Independent ID: 1a1b6d9a-a75c-e74d-ff84-ccbdf15091de
* Content: [Mail flow rules (transport rules) in Exchange Online](https://docs.microsoft.com/en-us/Exchange/security-and-compliance/mail-flow-rules/mail-flow-rules)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/mail-flow-rules/mail-flow-rules.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@philkloose  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @philkloose, thank you for your feedback.

I think we cannot say that there is an order for the actions you add to a rule. All the actions are executed with some exception. In the article you can find this information:
"Messages that match a rule's conditions get all the actions that are specified in the rule. For example, if the actions Prepend the subject of the message with and Add recipients to the Bcc box are selected, both actions are applied to the message.

Keep in mind that some actions (for example, the Delete the message without notifying anyone action) prevent subsequent rules from being applied to a message. Other actions (for example, the Forward the message) don't allow additional actions.

You can also set an action on a rule so that when that rule is applied, subsequent rules are not applied to the message."

You can also find more information here:
https://docs.microsoft.com/Exchange/security-and-compliance/mail-flow-rules/mail-flow-rule-actions

**Comment by scanum** [comment]
@philkloose Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
