### ISSUE TITLE
Exchange ActiveSync-compatible devices

### ISSUE THREAD

**Issue by manasrrp** [MicrosoftDocs/OfficeDocs-Exchange#1876]
Kindly put the complete list (Android, iOS, Windows Mobile, Black Berry etc) for ActiveSync compatible, so that we can choose the branded smart phone which are fully compatible with ActiveSync for enterprise use.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eefde9d-c209-c66f-1d5f-4e76b8df3e39
* Version Independent ID: fa7cecd2-88e1-5148-acf9-48f42a107f43
* Content: [Mobile phone and tablet features: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/mobile-phone-and-tablet-features-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/mobile-phone-and-tablet-features-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/mobile-phone-and-tablet-features-exchange-2013-help.md)
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@manasrrp Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @manasrrp, thank you for your feedback and help us to improve docs.microsoft.com.

I think it´s not possible to add an extensive list of all the devices manufacturers, mainly because Android manufacturers list is very extensive, I think it´s not possible to have a complete list. Any iPhone and iPad supported by Apple are supported to connect to Exchange.
About Android, any device that supports Outlook, GMail and Samsung Email app should work.

More information:
https://docs.microsoft.com/office365/servicedescriptions/exchange-online-service-description/clients-and-mobile-devices#outlook-for-ios-android-and-windows-phone

**Comment by scanum** [comment]
@manasrrp Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
