### ISSUE TITLE
Missing details

### ISSUE THREAD

**Issue by ros-financial-com** [MicrosoftDocs/OfficeDocs-Exchange#189]
I came to this documentation via the search query "Exchange Server ECP mail flow find mails send to mailbox".
As there are very limited ways to select options for a search, I think I tried all of them. Nevertheless my "EAC delivery reports" is unable to show a list of mails send TO the selected mailbox instead of mails send FROM the selected mailbox.
I would expect to get a list of mails send TO $USER1, when entering $USER1 into the field "*Mailbox to search:" and select the option "Search for messages sent to:" with the exact same $USER1. What I do get is a list of mails sent FROM $USER1 TO $USER1. The logic of this escapes me (and all of my team).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a0ce547-b985-bf9f-451c-ab792b1c83d2
* Version Independent ID: 9c5fed5d-16a3-2ca6-0cc1-205197b817f5
* Content: [Track messages with delivery reports](https://docs.microsoft.com/en-us/exchange/mail-flow/transport-logs/track-messages-with-delivery-reports?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/mail-flow/transport-logs/track-messages-with-delivery-reports.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/mail-flow/transport-logs/track-messages-with-delivery-reports.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by AndreaBarr** [comment]
@ros-financial-com Thank you for this feedback

I want to make sure we get you prompt assistance with your EAC delivery reports not showing a list of mails sent to a selected mailbox. Support has resources we don't have here in order to assist you in the most efficient way. I would like to have you open a Support ticket so that we can document and investigate this issue promptly for you. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
