### ISSUE TITLE
Calendar Free busy

### ISSUE THREAD

**Issue by merwindz** [MicrosoftDocs/OfficeDocs-Exchange#1890]
Does this migration process will help the users to look up for free busy time during the mailbox migration?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@merwindz This behavior might be a little unpredictable (which is why it is not documented), but what you should see is that users in one environment should be able to see free/busy information for users in that same environment. That is, if UserA has been migrated and UserB has not yet been migrated, then they would not be able to see free/busy information for each other until the migration of both user mailboxes is complete. There is no way to guarantee that you can view free/busy information until the migration has completed.

Because this is not very predictable behavior in the middle of a migration, I don't think there's anything to document here, so I will close this issue now, but please feel free to open a new issue if you find problems with the documentation.

**Comment by merwindz** [comment]
OK understood. 

Do you know if this migration process can also migrate distribution list to Exchange Online? The migration limitation section in the document doesn't mention anything about it.
