### ISSUE TITLE
Automatic mail forwarding no longer working

### ISSUE THREAD

**Issue by Joepvtilburg** [MicrosoftDocs/OfficeDocs-Exchange#1907]
This used to work (it did in my first two batches) but it no longer does and I see the following error in the migration status:

Data migrated: 36.05 GB ‎(38,713,680,595 bytes)‎
Migration rate: 0 B ‎(0 bytes)‎
Last successful sync date: 4/7/2020 7:00:57 PM
Error: TooManyTransientFailureRetriesPermanentException/BadRequestWebTransientException/WebException: Error: The job encountered too many transient failures ‎(102)‎ and is quitting. The most common failure is BadRequestWebTransientException/WebException with the hit count 60. --&gt; The web server responded with a 400 Bad Request error. Uri: https://www.googleapis.com/gmail/v1/users/user@domain.com/settings/forwardingAddresses --&gt; The remote server returned an error: ‎(400)‎ Bad Request.

the user@domain.com is obviously changed here

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 963b7331-1f6d-0400-d004-59797a4e87d1
* Version Independent ID: 71f2a5dd-0581-d33a-c41a-bef0ed1f208c
* Content: [Perform a G Suite migration](https://docs.microsoft.com/en-us/exchange/mailbox-migration/perform-g-suite-migration)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/perform-G-Suite-migration.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by mattpennathe3rd** [comment]
@Joepvtilburg Thanks for opening this issue. I'm not sure this is a documentation problem, and I've not seen any other reports of this here, so it might just be a temporary operations issue rather than a problem with this article.

Unfortunately, I'm not a support rep (I only work on the docs), so the best I can suggest is to contact support to see if they can help work through it with you.

I will close this issue for now, but if it turns out there's a problem with the article, please let me know (either by commenting again here or opening a new issue) and I'll gladly work with you to correct it.
