### ISSUE TITLE
Initialize-ADSyncGroupWriteBack Not in Module

### ISSUE THREAD

**Issue by danmyhre** [MicrosoftDocs/OfficeDocs-Exchange#193]
This function is no longer in the AdSyncPrep module

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33b5e7da-2e4a-7db9-43e2-27820bff540f
* Version Independent ID: da613e0a-6aee-bfe0-0449-8ef5fe14fc80
* Content: [Configure Office 365 Groups with on-premises Exchange hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-office-365-groups)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-office-365-groups.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @dstrome
* Microsoft Alias: **dstrome**

**Comment by NeighborGeek** [comment]
I'm also running into this same issue.  After importing the adsyncprep module, I ran "get-command -module adsyncprep" and the command Initialize-ADSyncGroupWriteBack is not shown in the list. 

Can we get an update on how to accomplish this?

**Comment by Cryptolaemus** [comment]
Same issue here. Would be great to have an update!

**Comment by robbo600** [comment]
Looks like the command/module has been deprecated/replaced, new module that needs importing is located below with a new syntax too...

`C:\Program Files\Microsoft Azure Active Directory Connect\AdSyncConfig\AdSyncConfig.psm1`

```
$AzureADConnectSWritebackAccountDN = <AAD_ account DN>
Import-Module "C:\Program Files\Microsoft Azure Active Directory Connect\AdSyncConfig\AdSyncConfig.psm1"
Set-ADSyncUnifiedGroupWritebackPermissions -ADConnectorAccountDN $AzureADConnectSWritebackAccountDN
```

**Comment by kenwith** [comment]
@dstrome - @dariomws306 is helping to solve this issue but is struggling with getting a sample environment setup to validate since it is a very complex scenario that will require a public cert. He has been researching and THINKS this will work ( http://blog.icewolf.ch/archive/2018/12/03/azure-active-directory-connect-group-writeback.aspx ) but want's to get your thoughts and figure out how we can validate and if the ideas from that blog could be somehow incorporate into the official docs.. 

What do you think?

Also, @danmyhre and @NeighborGeek and @Cryptolaemus --- really appreciate you engaging in this conversation and helping us work through this to make the content better! If you have more ideas too please share here and as @dariomws306 creates the Pull Request to make modifications to the docs he will post the link here so everyone can review. One last thing, the docs are open source so anyone can feel free to make a PR to make a change request.. I think it will require some effort on this one and Dario can take the lead with guidance from @dstrome who leads the Exchange team.
