### ISSUE TITLE
Journaling Safety Net

### ISSUE THREAD

**Issue by felgar73** [MicrosoftDocs/OfficeDocs-Exchange#2049]
Is the two-day expiration for queued journal reports something we can modify? I heard this was being reduced to 24 hrs, which is troubling.

-thnx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 598506d9-01d0-fd2e-2600-9b5557e427f1
* Version Independent ID: 88fdfd05-dcde-4745-03f4-fb271a3c7094
* Content: [Configure Journaling in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/journaling/configure-journaling)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/journaling/configure-journaling.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/journaling/configure-journaling.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @mattpennathe3rd
* Microsoft Alias: **v-mapenn**

**Comment by scanum** [comment]
@felgar73  Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @felgar73 Felix how are you?
I am afraid you can not customize the message deferral limit, which in fact it is 24 hours since 2019. (MC173908)
More information [here](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-protection-service-description/exchange-online-protection-limits).

I searched on UserVoice and there is an entry about this [here](https://office365.uservoice.com/forums/289138-office-365-security-compliance/suggestions/11514936-allow-settings-for-message-expiration-timeout-inte) with a reply from the product team about current state of the feature.

I hope this information is valuable for you.

**Comment by felgar73** [comment]
Thanks Andres, I appreciate the response.

-Felix G.
PFE – Exchange | Microsoft

**Comment by scanum** [comment]
@felgar73 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
