### ISSUE TITLE
Traditional Chinese Traslation Need to Be Improved.

### ISSUE THREAD

**Issue by GGJason** [MicrosoftDocs/OfficeDocs-Exchange#2081]
I found that some Traditional Chinese translation contains English sentences ([the page link](https://docs.microsoft.com/zh-tw/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365#step-by-step-instructions-for-direct-send) ) but the only repo about the docs is this one. Is there any repo that I can contribute to improve the translation?

**Comment by mattpennathe3rd** [comment]
@GGJason Thanks for pointing this out. Many of the articles in this repo are machine translated, but the one you linked is a high-traffic article and is human translated. I'm not certain why there are English sentences throughout, as this seems rather random.

I will contact our localization team to see if this can be improved. I'll also raise the issue of community-contributed translations, as this could be very helpful.

Thanks again for pointing this out. Someone else will follow up with you.

@msdmaguire For visibility and handoff.

**Comment by mattpennathe3rd** [comment]
@GGJason I passed this on to our localization team and they are working on it. I will close this issue now because the work will be done by a different team, but thank you again for pointing this out.

As for contributing to translations of our docs, I am told that we are exploring this for the future, so there might be opportunities for you to help at a later time. Please continue to check the Docs site for news on this and thank you very much for offering.

**Comment by TinaMcN** [comment]
@OfficeGlobal please fix this issue.   The same issue happens for the other languages also.
