### ISSUE TITLE
Not a technical issue

### ISSUE THREAD

**Issue by snydertl** [MicrosoftDocs/OfficeDocs-Exchange#2184]
I work in a GCC environment and a big suggestion would be to put all things that affect GCC in a single place.  It took multiple searches to find out that the GCC side doesn't have specific features.  Having this information in one place would greatly help those of us in this situation and I believe reduce the number of incidents opened. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ba22add1-5185-c5b2-8520-c47855559a7a
* Version Independent ID: f79f12a8-fb77-5a0f-d152-441394373673
* Content: [Using Outlook for iOS and Android in the Government Community Cloud](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-in-the-government-cloud)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-in-the-government-cloud.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-in-the-government-cloud.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@snydertl Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by msdmaguire** [comment]
Hi @snydertl, thank you for the feedback. Our current policy is to treat every component and feature as though it applies to every tenant (GCC or non-GCC alike), UNLESS there is an exception. When there is an exception, such as when something does not apply to GCC or is not available in GCC, we call that out with a note. Your suggestion is a good one, but internally the logistics would be challenging. This is because the product group is continually working to bring GCC tenants on par with global tenants, so it's always an evolving story that would be difficult to maintain and keep current. I hope this explanation makes sense to you and I'm sorry if it disappoints. I thank you again, and we do appreciate any and all feedback we receive from customers.
