### ISSUE TITLE
Solution to route messages to the groups domain if DNS is not pointing to EXO 

### ISSUE THREAD

**Issue by FrankCarius** [MicrosoftDocs/OfficeDocs-Exchange#2347]
The Statement "f the MX DNS record for the group domain is set to the on-premises Exchange server, mail flow won't work correctly between users in the on-premises Exchange organization and the Microsoft 365 or Office 365 group." ist correct but you should also offer a solution for that case.
The Admin can change the routing of the "Outbound to Office 365"-Connector from MX to Smarthost via "tenantname-mail-onmicrosoft-com.mail.protection.outlook.com".   This will do the trick in that case, that the DNS-Domain is routed via Onprem Systems. 

Frank

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 459e11a9-aa70-1757-15d6-45e3292aad09
* Version Independent ID: 13a6d8d0-1a41-1c75-6042-f96d1855facf
* Content: [Configure Microsoft 365 Groups with on-premises Exchange hybrid](https://docs.microsoft.com/en-us/exchange/hybrid-deployment/set-up-microsoft-365-groups)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment/set-up-microsoft-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment/set-up-microsoft-365-groups.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@FrankCarius Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @FrankCarius, thank you for your feedback and help us to improve docs.microsoft.com.

I know your blog, and it's really amazing, very useful information.

I'm thinking about the impact of routing these emails through an SMTP smart host/gateway, and I need to check if I can add this sentence here due to supportability.

**Comment by dariomws** [comment]
@FrankCarius if you're fully convinced that we should add it I'll try to confirm with the product team. Please let me know. Thanks!

**Comment by FrankCarius** [comment]
The current description with the following commandlet is wong, if the customers routes "groups.contoso.com" to OnPrem.

`Set-SendConnector` -Identity "Outbound to Office 365" -AddressSpaces "contoso.mail.onmicrosoft.com","groups.contoso.com"

I think, a experiened Admin is able to fix this but ..
And i'ld like to have "contoso.onmicrosoft.com" also added to the connector by HCW to make sure, that even mails with the default domain are not routet via internet, because they will not arrive due "RequireSenderAuthenticationEnabled:true"

I will add an blog atricle about "routing M365 groups" anyway :-).

**Comment by dariomws** [comment]
@FrankCarius thank you!

I understand that, but the instructions in this article set the MX record to O365, so I think that this command is ok.

I think I understand you, but my problem here is that all the instructions (and the caution note) in the article are based on the MX pointing to O365.
If you think it's essential to add a way to set the MX to on-premises, I need to double-check with the author because I think the article was intentionally written with this information.

Please let me know. Thank you again!

**Comment by scanum** [comment]
@FrankCarius  We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
