### ISSUE TITLE
Restricting access to Discovery Managers

### ISSUE THREAD

**Issue by iragusa67** [MicrosoftDocs/OfficeDocs-Exchange#2406]
I think it's also important to note that the use of compliance boundaries could be implemented in order to restrict what areas an eDiscovery manager can search in 365.  [https://docs.microsoft.com/en-us/microsoft-365/compliance/set-up-compliance-boundaries?view=o365-worldwide](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 70987f04-a3ed-23d2-f7a9-4f8b2c321753
* Version Independent ID: f5bf710c-d0f4-ac00-be57-f9f33c7b9276
* Content: [Assign eDiscovery permissions in Exchange](https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-ediscovery/assign-ediscovery-permissions)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/assign-ediscovery-permissions.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/assign-ediscovery-permissions.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@iragusa67 PR has been copyedited and is ready for final review, could you please check and merge? Thanks!

**Comment by dariomws** [comment]
Hi @iragusa67, thank you for your feedback and help us to improve docs.microsoft.com.

I have to redirect you to the following link:
https://docs.microsoft.com/microsoft-365/compliance/assign-ediscovery-permissions
On the left navigation, you can find the "Set up compliance boundaries" article.

This is because In-Place eDiscovery in the Exchange admin center (EAC) has been retired. For more information, see the note at the beginning of the following article:
https://docs.microsoft.com/exchange/security-and-compliance/in-place-ediscovery/in-place-ediscovery

**Comment by scanum** [comment]
@iragusa67 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
