### ISSUE TITLE
Request to remove mention of throughput values

### ISSUE THREAD

**Issue by Kovai-MSFT** [MicrosoftDocs/OfficeDocs-Exchange#2421]
[Enter feedback here]
The reference on 30GB/Hour migration throughput mentioned in this article is not in alignment with article https://docs.microsoft.com/en-us/exchange/mailbox-migration/office-365-migration-best-practices#estimated-migration-times, this can sound confusing for customers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8e039381-d57f-0a0f-18d5-933193b3e46a
* Version Independent ID: db0172fb-26a7-6833-a8f3-6d5609a10e16
* Content: [Performance factors and best practices for hybrid migrations](https://docs.microsoft.com/en-us/exchange/performance-best-practices)
* Content Source: [Exchange/ExchangeHybrid/performance-best-practices.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/performance-best-practices.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
@Kovai-MSFT Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @Kovai-MSFT 

While I investigate this issue, 
are you a Microsoft employee?

If you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=Kovai-MSFT

Thanks

**Comment by Kovai-MSFT** [comment]
Okay, thanks Andres, I've now completed linking my corp account and GitHub account

**Comment by get-itips** [comment]
Hello @Kovai-MSFT I've been analyzing this and I would like to invite @dariomws to this conversation to have another opinion, in my opinion, both documents can be valid, the 30 GB/hour throughput indicated by this article is just an example achieved with specific hardware and settings, and the other article exposes more general performance numbers.
As one of the articles says "Because of differences in how migrations are performed and when they're performed, your actual migration velocity may vary." so these documents should be taken as a reference and not as the actual performance in all scenarios.

**Comment by dariomws** [comment]
Agree with you @get-itips; I think the 30 GB/hour throughput is just an example. Up to 100 GB/hour throughput in some customers and 30 GB/hour throughput using the hardware configuration provided in the example.

**Comment by Kovai-MSFT** [comment]
Okay, the ask was raised as customers confuse these statements, but what you mentioned makes sense, we will educate customers accordingly, shall close this out.  Thanks both of you!

**Comment by dariomws** [comment]
Thank you @Kovai-MSFT!
