### ISSUE TITLE
Pull instead of push 

### ISSUE THREAD

**Issue by jlfinkels** [MicrosoftDocs/OfficeDocs-Exchange#243]
Is there any way to pull messages, calendar updates and contacts on a scheduled basis, I.e. hourly, instead of only having a push setting?

**Comment by AndreaBarr** [comment]
@jlfinkels Thank you for this inquiry

I am not sure if there is a way to pull these down instead of just only having a push setting. I will get this over to the Exchange team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by jlfinkels** [comment]
Thank you for the consideration. It is all about battery life as many expect more from our phones than the current batteries can support in a 24-hour window. Everything we can do to conserve power is a good thing.


________________________________

**Comment by chrisda** [comment]
@jlfinkels is there a specific topic that you're commenting on?
