### ISSUE TITLE
This article is not accurate at all, regarding MFA.

### ISSUE THREAD

**Issue by smplcoder** [MicrosoftDocs/OfficeDocs-Exchange#2626]
A call back from US Microsoft support confirmed the several warnings here are not correct stating that SMTP Auth cannot be used with MFA - in fact SMTP Auth should NOT be used WITHOUT MFA and an App Password enabled to secure your service, this article should be re-written to accurately show that instead of being plastered with warnings to not use MFA.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @smplcoder, thank you for your feedback.

@Benny-54 could you kindly help here? I want to know if there is a planning update for this article. If not, I can do it as it requires a whole update. For example:

- SMTP AUTH now support Modern Auth (so MFA): https://techcommunity.microsoft.com/t5/exchange-team-blog/announcing-oauth-2-0-support-for-imap-and-smtp-auth-protocols-in/ba-p/1330432
- Security defaults note is ok as it disables SMTP AUTH. But it cannot be the recommended option anymore. I think the recommended options in order should be: Option 2, 3, and then 1 (SMTP AUTH). https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-february-2021-update/ba-p/2111904
- If SMTP AUTH is used, OAUTH should be the preference instead of legacy auth.

**Comment by Benny-54** [comment]
Hi @JoanneHendrickson, could you please look into this?

**Comment by dariomws** [comment]
Hi @JoanneHendrickson, could you please help here?

**Comment by dariomws** [comment]
Hi @JoanneHendrickson, could you please help here?

**Comment by JoanneHendrickson** [comment]
Topic updated.
