### ISSUE TITLE
Need Clarification on referenced information from 2014.

### ISSUE THREAD

**Issue by rstraker** [MicrosoftDocs/OfficeDocs-Exchange#2653]
In the section: Why you may not want to decommission Exchange servers from on-premises, there is a blog post referenced that is last updated in 2014 and talks about using Exchange 2010 and DirSync.  This information is causing my customer to believe that they must keep Exchange Servers on-premises or they cannot manage their users.  Is this information still accurate in 2021?  Is it impossible for customers to remove all Exchange Services from on-premises and keep using Azure ADConnect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6eb1f9b-27f6-4d93-5a97-ad3f8b6ed27d
* Version Independent ID: f248ffa0-1bc3-be8f-055a-1c941e3ad234
* Content: [How and when to decommission your on-premises Exchange servers in a hybrid deployment](https://docs.microsoft.com/en-us/exchange/decommission-on-premises-exchange?redirectedfrom=MSDN)
* Content Source: [Exchange/ExchangeHybrid/decommission-on-premises-exchange.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/decommission-on-premises-exchange.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by dariomws** [comment]
Hi @rstraker, thank you for your feedback.

This article is accurate and up to date. You must keep at least one Exchange Server on-premises if you are using Azure AD Connect.
The blog article is referenced to provide more information about why you need to keep that server(s). The reason is still valid.

**Comment by rstraker** [comment]
Dario,

Thank you for the reply.  So I'm to understand that the Blog article is correct and I must use DirSync and Exchange 2010 as stated in the Blog?

Bob

**Comment by dariomws** [comment]
@rstraker, all the information is here:
https://docs.microsoft.com/exchange/decommission-on-premises-exchange

The link contains some historical information about why you need to keep Exchange if you are using Azure AD Connect. If you want to have more context, you can read it.

**Comment by dariomws** [comment]
"**Why you may not want to decommission Exchange servers from on-premises**
Customers with a hybrid configuration often find after a period of time that all of their mailboxes have been moved to Exchange Online. At this point, they may decide to remove the Exchange servers from on-premises. However, they discover that they can no longer manage their cloud mailboxes.

**When directory synchronization is enabled for a tenant and a user is synchronized from on-premises, most of the attributes cannot be managed from Exchange Online and must be managed from on-premises**. This is not due to the hybrid configuration, but it occurs because of directory synchronization. In addition, even if you have directory synchronization in place without running the Hybrid Configuration Wizard, you still cannot manage most of the recipient tasks from the cloud."

Also here:
"Since the customer is planning on keeping AD FS, they will also have to keep directory synchronization since it is a prerequisite. Because of that, **they cannot fully remove the Exchange servers from the on-premises environment**. However, they can decommission most of the Exchange servers, but leave a couple of servers behind for user management. Keep in mind that the servers that are left running can be run on virtual machines since the workload is almost completely shifted to Exchange Online."

**Comment by rstraker** [comment]
Thank you Dario

**Comment by dariomws** [comment]
@scanum I think we can close this issue. Thanks!

**Comment by dariomws** [comment]
@scanum I think we can close this issue. Thanks!
