### ISSUE TITLE
Exchange Online Plan 2 DLP?

### ISSUE THREAD

**Issue by parental-unit-2** [MicrosoftDocs/OfficeDocs-Exchange#2781]
With deprecation of "Legacy Exchange Online data loss prevention" (DLP), are Exchange Online Plan 2 customers losing access to DLP functionality?
Exchange Online Plan 2 currently offers legacy DLP:
https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description
Exchange Online Plan 2 is not listed as qualifying for the newer (post-legacy) Office 365 DLP functionality:
https://docs.microsoft.com/en-us/office365/servicedescriptions/microsoft-365-service-descriptions/microsoft-365-tenantlevel-services-licensing-guidance/microsoft-365-security-compliance-licensing-guidance#which-licenses-provide-the-rights-for-a-user-to-benefit-from-the-service-6
Exchange Online Plan 2 is also not listed as a qualifying license for the DLP policy migration preview feature:
https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-migrate-exo-policy-to-unified-dlp?view=o365-worldwide#licensing-and-versions
So, will Exchange Online Plan 2 customers lose all DLP functionality and policy when legacy DLP is retired?
Thanks for any clarification,
Rob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a32c304f-a00c-5d66-d3e2-9ddf700d121e
* Version Independent ID: 0bb81f36-0b92-263a-6ee1-9b282f20a44d
* Content: [Data loss prevention](https://docs.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/data-loss-prevention)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/data-loss-prevention.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/data-loss-prevention/data-loss-prevention.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
Thank you for submitting feedback and contributing to the docs. We are currently investigating this.

**Comment by get-itips** [comment]
Hello @parental-unit-2 

How are you?

I've been digging into this since a long time, I checked and now the article 

https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description

for Plan 2, Data Loss Prevention says **No**. Probably referring to the new DLP.

**Also a note was added to this article describing what will be the DLP functionality available once it is retired**

https://docs.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/data-loss-prevention


>Legacy Exchange Online data loss prevention in the Exchange admin center is in the process of being deprecated. We recommend that you create DLP policies in the Microsoft 365 compliance center. For more information about this DLP, see [Learn about data loss prevention](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-learn-about-dlp).

>Starting April 1, 2022, admins will no longer be able to make configuration changes to DLP policies in the classic Exchange admin center. Existing rules will continue to work as-is.
Starting August 1, 2022, the DLP policy management experience in the classic Exchange admin center will be retired. Admins will still be able to view the associated rules in read-only mode using the mail flow rule (transport rule) experience.
You can easily migrate your legacy Exchange Online DLP policies using the migration wizard. For more information, see [Migrate Exchange Online data loss prevention policies to the Microsoft 365 compliance center](https://docs.microsoft.com/en-us/microsoft-365/compliance/dlp-migrate-exo-policy-to-unified-dlp).

Hope this information helps you,

**Comment by get-itips** [comment]
@scanum

**Comment by brsieff** [comment]
@scanum Hello, do you have any updates on this? I have the same question, there is conflicting information between the Exchange Online Service description indicating DLP with Exchange Online Plan 2 is not offered, whereas the [Installation Prerequisites within the Data Loss Prevention article](https://docs.microsoft.com/en-us/exchange/security-and-compliance/data-loss-prevention/data-loss-prevention#installation-prerequisites) indicates "In order to make use of DLP features, **you must have at least one mailbox with an Exchange Online Plan 2 license configured**. For more information, see [Exchange Online service description](https://docs.microsoft.com/en-us/office365/servicedescriptions/exchange-online-service-description/exchange-online-service-description). Is there a way we can get some clarification if DLP is indeed part of Exchange Online Plan 2 or not? I have a customer with O365 E1 + Exchange Online Plan 2 so this will be crucial for their migration to Exchange Online if they actually get DLP with this move or not given their current licensing.
