### ISSUE TITLE
End-user experience on Outlook Mobile if their mailbox is on-premises and their mailbox gets migrated to EXO

### ISSUE THREAD

**Issue by SLeuthold** [MicrosoftDocs/OfficeDocs-Exchange#2815]
Please qualify this Q&A paid and add to the Q&A towards the bottom of the article....

o	Question: If an end-user is leveraging Outlook Mobile with their mailbox on-premises, what will their experience be after their mailbox is migrated to Exchange Online?

o	Answer: End-users will not need to reconfigure Outlook Mobile, as long as Outlook Mobile was originally configured with hybrid modern auth (HMA). If they configured Outlook Mobile using basic authentication, they will need to reconfigure their mail profile after the mailbox has been migrated.

**Comment by scanum** [comment]
@SLeuthold Please link the article you are referring to. Thanks.

**Comment by dariomws** [comment]
Hi @SLeuthold, thank you for your feedback.

I'm not sure to add this information. From the different articles in this section:

Outlook for iOS and Android uses Basic authentication with Exchange ActiveSync in the following environments:

- In Exchange Server 2010 environments

- When a hybrid relationship with Microsoft 365 or Office 365 has not been configured

- When hybrid Modern Authentication has not been enabled

So I understand that if you are using a hybrid Exchange, Outlook Mobile will connect using Modern Authentication to Exchange Online no matter if the mailbox is located on-premises or online. Other clients like the native apps will connect directly to the on-premises Exchange servers using Activesync protocol and basic authentication. When you enable hybrid Modern Authentication, you only allow Outlook Mobile in your hybrid environment by blocking other scenarios like:
- OAuth capable Exchange ActiveSync clients
- Exchange ActiveSync clients using basic authentication
- Exchange Web Services, IMAP4, or POP3 protocols with basic authentication

Conclusion: I think that for hybrid environments (with or without hybrid MA), Outlook Mobile won't need to be reconfigured
because it's always connected to Exchange Online using Modern Auth. After migration, the difference is that Exchange Online won't synchronize to an on-premises as the mailbox is now there.
