### ISSUE TITLE
.Net version listed for prereqs is incorrect

### ISSUE THREAD

**Issue by a2geekgirl** [MicrosoftDocs/OfficeDocs-Exchange#2856]
I had to schedule down time with my client to get .Net 4.6.2 installed only to find out when we went to run the hybrid config wizard that contrary to your documentation .Net 4.7.2 is required. We are now set back in our deployment timeline due to the need to schedule additional downtime for the reboot from the .Net 4.7.2 install. It would have been nice if the prereq documentation was accurate and we only had to schedule 1 reboot instead of 2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2ddce84-2ec9-3744-1a3f-20303275affa
* Version Independent ID: 2c5ba0fc-80c4-8de0-61ba-5e73bf558766
* Content: [Hybrid deployment prerequisites](https://docs.microsoft.com/en-us/exchange/hybrid-deployment-prerequisites)
* Content Source: [Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeHybrid/hybrid-deployment-prerequisites.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **serdars**

**Comment by dariomws** [comment]
Hi @a2geekgirl, thank you for your feedback.

I'll update the article because 4.7.2 is the latest version supported in a hybrid environment, not only for the Hybrid Configuration Wizard:
"Hybrid deployments require the latest Cumulative Update (CU) or Update Rollup (RU) that's available for your version of Exchange. If you can't install the latest update, the immediately previous release is also supported."

With this in mind, supported version/CUs the Exchange in a hybrid configuration:
- Exchange 2019 CU11 and 10 (require at least .net 4.8)
- Exchange 2016 CU22 and 21 (require at least .net 4.8)
- Exchange 2013 CU23 (require at least .net 4.7.2)

Please review your environment because if you weren't running .net 4.6.2 maybe you don't have a supported CU installed.

**Comment by a2geekgirl** [comment]
Thanks Dario,

In this instance it was for an Exchange 2010 SP3 CU29 server. Client had technical reasons they could not patch, so we manually installed .Net 4.6.2, scheduled an emergency reboot, and were prompted for .Net 4.7.2 immediately when we ran the HCW.

Thanks,

Michelle Checchi
Microsoft 365 Engineer
M: 734-904-9224
***@***.******@***.***>

Applied Information Sciences (AIS)
www.AppliedIS.com<https://www.appliedis.com/>

**Comment by dariomws** [comment]
@a2geekgirl, ok, please remember that Exchange 2010 is out of support.

**Comment by a2geekgirl** [comment]
Yep, which is why we’re getting this client moved to M365 😊

Thanks,

Michelle Checchi
Microsoft 365 Engineer
M: 734-904-9224
***@***.******@***.***>

Applied Information Sciences (AIS)
www.AppliedIS.com<https://www.appliedis.com/>
