### ISSUE TITLE
SMTP relay is unsupported. Article should be updated with a clear statement

### ISSUE THREAD

**Issue by JeroenDronkers** [MicrosoftDocs/OfficeDocs-Exchange#2908]
****
[SMTP relay as documented in this article is not anymore supported by Microsoft since it relies on functionality used by Exchange 2003 (IIS 6.0). In support we receive cases daily about it. It would be great if this article could be updated with a clear statement that smtp relay with IIS is unsupported.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f1e4e3f0-bb9c-cca0-9343-49926262caba
* Version Independent ID: 75645bf5-f9a5-b5b9-d9e6-856e32ffc97f
* Content: [How to set up a multifunction device or application to send email using Microsoft 365 or Office 365](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365)
* Content Source: [Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @JeroenDronkers, thank you for your feedback.

I'm not sure if understand. Could you provide more detail? Which of the three options are you talking about? I cannot find any mention of IIS here.

In addition, if you have a Microsoft alias, you can link your accounts in GitHub so that a blue "Microsoft submitter" label appears to any PR's or issue you submit. Guidance on it here: https://docs.opensource.microsoft.com/tools/github/index.html

Here is the site you can use to see the mappings between GitHub and Microsoft aliases: https://repos.opensource.microsoft.com/people?q=JeroenDronkers
