### ISSUE TITLE
Autodiscover

### ISSUE THREAD

**Issue by lightupdifire** [MicrosoftDocs/OfficeDocs-Exchange#2963]
Hello,

Can you please confirm that Autodiscover is not in the scope for deprecation of Basic authentication in Exchange Online?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 19cf826a-aaf1-91ed-8a8f-637d869e47df
* Version Independent ID: 61d69fb6-184d-acf5-8b02-39b3d885d28b
* Content: [Deprecation of Basic authentication in Exchange Online](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by scanum** [comment]
@JohanFreelancer9 Copy editing is needed for this PR. Thanks.

**Comment by JohanFreelancer9** [comment]
@scanum, PR needs to be created.

**Comment by dariomws** [comment]
Hi @lightupdifire, thank you for your feedback.

I confirm that Autodiscover is not included in the article because there is no estimated time to disable Basic Auth for this service.
For more information, see [Basic Authentication and Exchange Online – February 2021 Update](https://techcommunity.microsoft.com/t5/exchange-team-blog/basic-authentication-and-exchange-online-february-2021-update/ba-p/2111904).

**Comment by lightupdifire** [comment]
Thanks!
