### ISSUE TITLE
Missing content

### ISSUE THREAD

**Issue by Blewis-Copperleaf** [MicrosoftDocs/OfficeDocs-Exchange#3016]
This page has good information about the policy, but does not point to where/how to edit the policy, even though it is explicitly stated that can be done.  How about at least a link to another page that has this information?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f5be8284-bc52-a254-97eb-ef44b3cb002a
* Version Independent ID: 25c499c9-c274-933d-6c56-ae126c32079e
* Content: [Default Retention Policy in Exchange Online](https://docs.microsoft.com/en-us/exchange/security-and-compliance/messaging-records-management/default-retention-policy)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/default-retention-policy.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/messaging-records-management/default-retention-policy.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @JoanneHendrickson
* Microsoft Alias: **jhendr**

**Comment by dariomws** [comment]
Hi @Blewis-Copperleaf, thank you for your feedback.

I suggest that you use the M365 Compliance Center instead of Retention Policies in Exchange Online as stated in the first note of the article.

To edit existing policies, you can use the link "Create a Retention Policy in Exchange Online" at the end of the article. The only difference between creating a new policy and editing one is that you need to click Edit (the pencil) instead of Add (plus symbol).

And I want to take advantage of this comment, to remember you that the classic EAC is being retired by the end of this year:
https://techcommunity.microsoft.com/t5/exchange-team-blog/deprecation-of-the-classic-exchange-admin-center-in-ww-service/ba-p/2736358
