### ISSUE TITLE
Instructions are confusing for creating MX records

### ISSUE THREAD

**Issue by scoperetail** [MicrosoftDocs/OfficeDocs-Exchange#3029]
Instructions for creating MX records are not sufficient. It does not tell what to put in the data field. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2ec9bdfa-e5f7-a869-514d-0e6ae50ff7e9
* Version Independent ID: 87521d1b-8d1b-0648-9059-347cdae9d3f7
* Content: [Google Workspace migration prerequisites in Exchange Online](https://docs.microsoft.com/en-us/exchange/mailbox-migration/googleworkspace-migration-prerequisites)
* Content Source: [Exchange/ExchangeOnline/mailbox-migration/googleworkspace-migration-prerequisites.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/mailbox-migration/googleworkspace-migration-prerequisites.md)
* Service: **exchange-online**
* Technology: ****
* GitHub Login: @AshaIyengar21
* Microsoft Alias: **v-aiyengar**

**Comment by dariomws** [comment]
Hi @scoperetail, thank you for your feedback.

I think you're talking about the step 5:
"Log into your DNS provider and update your DNS records so that you have an MX record at the domain you created above in step 3, pointing to Microsoft 365 or Office 365. Ensure that this domain that you created above is an accepted domain in Microsoft 365 or Office 365. Follow the instructions in [Add a domain to Microsoft 365](https://docs.microsoft.com/microsoft-365/admin/setup/add-domain) to add the Microsoft 365 or Office 365 routing domain ("o365.fabrikaminc.net") to your organization and to configure DNS to route mail to Microsoft 365 or Office 365."

This sentence is redirecting you to the article to add the domain to Microsoft 365. When you add the domain in the Microsoft 365 Admin Center, you have the detailed instructions to create the MX record including the data field.
