### ISSUE TITLE
Target Delivery Domain Missing New Exchange Admin Center

### ISSUE THREAD

**Issue by mialtochi** [MicrosoftDocs/OfficeDocs-Exchange#3189]
Target Delivery Domain for Google Workspace Migration using the New Exchange Admin Center dropdown list is blank, or it is not showing all the Target Delivery Domains and you cannot type it

**Comment by technion** [comment]
This issue was raised and confirmed a while back:

https://github.com/MicrosoftDocs/OfficeDocs-Exchange/issues/3001

Closing it just means people like you presumably lost time on the same issue, as they have for over a year: https://answers.microsoft.com/en-us/msoffice/forum/all/gsuite-to-office-365-new-exchange-admin-center/6f427590-f3aa-48fd-9d40-0ef7bf26d1ae

The answer is that you have to use the classic admin center.
