### ISSUE TITLE
Clarification - self signed vs third party

### ISSUE THREAD

**Issue by jbostoen** [MicrosoftDocs/OfficeDocs-Exchange#338]
Could there be some clarification here? These documentation seem to suggest a self-signed certificate is okay for Federation Trust. However, the Microsoft Support and Recovery Assistant for Office 365 suggests it must be third party for federation services?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b3694c-16ed-97fb-1423-16d950922396
* Version Independent ID: fd8bf16d-7ed7-c0f9-3157-e11fc0653829
* Content: [Renew the federation certificate: Exchange 2013 Help](https://docs.microsoft.com/en-us/exchange/renew-the-federation-certificate-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/renew-the-federation-certificate-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/renew-the-federation-certificate-exchange-2013-help.md)
* Product: **exchange**
* GitHub Login: @dstrome

**Comment by AndreaBarr** [comment]
@jbostoen Thank you for this inquiry

I am not sure on if you need to have a third party or self assigned certificate for Federation Trusts. Let me get this over to the Exchange writing team for investigation. 


Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by AndreaBarr** [comment]
@MK-Kamal Could you please investigate this?

**Comment by sowjanya365** [comment]
Hi @jbostoen 

Thanks for reaching out!

To establish a federation trust with the Azure AD authentication system, either a self-signed certificate or an X.509 certificate signed by a certification authority (CA) must be created and installed on the Exchange server used to create the trust. We strongly recommend using a self-signed certificate, which is automatically created and installed using the Enable federation trust wizard in the EAC. 

Kindly let us know where exactly that you've observed that it must be third party for federation services? So that we can assist you in clarify your query. 

Thank you!

**Comment by scanum** [comment]
@jbostoen We appreciate any feedback that improves the content in the Microsoft docs but we haven't had any response from you so we are going to close this issue.  
 
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.
