### ISSUE TITLE
Source and target PF mailbox is locked

### ISSUE THREAD

**Issue by trudolf-msft** [MicrosoftDocs/OfficeDocs-Exchange#352]
Please double check

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: ea75864a-c5a5-0e83-f78b-7ce1f8c5239a
* Version Independent ID: ecc903e7-99d3-48fb-fb41-70a34da4aaf8
* Content: [Verschieben ein öffentliches Ordners auf eine andere Öffentliche Ordner-Postfach: Exchange 2013-Hilfe](https://docs.microsoft.com/de-de/exchange/move-a-public-folder-to-a-different-public-folder-mailbox-exchange-2013-help)
* Content Source: [Exchange/ExchangeServer2013/move-a-public-folder-to-a-different-public-folder-mailbox-exchange-2013-help.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer2013/move-a-public-folder-to-a-different-public-folder-mailbox-exchange-2013-help.md)
* Product: **exchange**
* GitHub Login: @olprod

**Comment by AndreaBarr** [comment]
@trudolf-msft Thank you for this feedback

If your PF mailbox is locked and it shouldn't be I would like to get you over to Support since they have more resources than we do to help find a resolution. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
