### ISSUE TITLE
Want minimal Hybrid install...

### ISSUE THREAD

**Issue by tymes** [MicrosoftDocs/OfficeDocs-Exchange#355]
So I had a 2016 before on this hybrid 365 too domain, but I've recently uninstalled it and now trying to reinstall but during install options while I would prefer "management tools" all options fail, so just one strange error denied access to 
"C:\Program Files\Microsoft\Exchange Server\V15\ClientAccess\Autodiscover\bin"  
but duh!, the install just installed and populated that folder itself...

anyway, I just want to click on Exchange and have it install. but have a minimal o365 install.

Err (stupid install) Errg (my feelings)

**Comment by AndreaBarr** [comment]
@tymes Thank you for this feedback

I am not sure how to answer this for you. I want to get you over to Support since they have the resources needed to find a resolution for this. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
