### ISSUE TITLE
Misleading - in front of email address.

### ISSUE THREAD

**Issue by jsmcnair** [MicrosoftDocs/OfficeDocs-Exchange#360]
I'm not sure if a leading `-` in an email address is valid, but it's probably misleading to someone who is not used to PowerShell, who might think it is required in front of any email address.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d76e96a-b0a9-552b-e0cf-fa5a1caeee85
* Version Independent ID: 93a0041c-a6ea-0255-0127-a2ad8d4ba436
* Content: [Increase the space used by Inbox rules](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-on-the-web/increase-the-space-used-by-inbox-rules)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-on-the-web/increase-the-space-used-by-inbox-rules.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-on-the-web/increase-the-space-used-by-inbox-rules.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by chrisda** [comment]
@jsmcnair, in addition to that typo you found, I've determined that the entire direction of that topic has now changed; the default Inbox rules quota in a E5 and E3 tenant that I have access to is 256 KB (the maximum that you can set). So, I changed the direction of the topic to modifying the quota instead of increasing it. I also included more interesting ways to bulk apply quota values.

Thanks for the feedback.

**Comment by jsmcnair** [comment]
For info - I changed this on a mailbox that has been in existence for a long time. It may even have been migrated from an old Exchange 2003 organisation. The value was 64KB, which would probably have been an old default, so it’s fair to say that someone reaching this documentation is likely doing so because they have old mailboxes.
