### ISSUE TITLE
Update software requirements

### ISSUE THREAD

**Issue by shackdaddyoly** [MicrosoftDocs/OfficeDocs-Exchange#4]
Could you amend them to include Windows 2016 Server?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f86fd86b-1922-7d3e-7498-48ae02acbfc8
* Version Independent ID: c053c92a-1619-0e3b-1c0a-9d4c36174df2
* Content: [Plan for high availability and site resilience](https://docs.microsoft.com/en-us/Exchange/high-availability/plan-ha)
* Content Source: [Exchange/ExchangeServer/high-availability/plan-ha.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/high-availability/plan-ha.md)
* Product: **exchange-server-itpro**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by msdmaguire** [comment]
Thanks for the suggestion. Two sections prior are links to Exchange 2016 prereqs and Exchange 2016 system prereqs, which both include Windows 2016. Since Windows 2016 is just one of many requirements for HA in Exchange 2016, we're wary of having people not read the full sets of prereqs listed in those two linked articles.
