### ISSUE TITLE
Clarification suggestions

### ISSUE THREAD

**Issue by jremmc** [MicrosoftDocs/OfficeDocs-Exchange#472]
Re: Use batch migration to migrate Exchange 2010 public folders to Exchange 2016 document: Explain why command to look for \ in folder name contains a forward slash / as well, and whether to ignore system public folders. My results only returned system public folders, and the Name did not show a back slash \ , only a forward slash /. And Name did not return enough info to identify the folders, I had to search the Legacy_PublicFolderStatistics.xml to find out they were system public folders. 

Also, this did not work for me: 
((get-mailbox -Arbitration -Identity Migration.*).servername -eq (hostname))

I used Get-Mailbox -Arbitration -Identity Migration.* -DomainController <name of one of the root DCs> instead.

**Comment by nenonix** [comment]
@jremmc Thank you for contributing feedback to improve Microsoft Docs.. I need your help to reflect this information in the content. Firstly what document are you referring to? (Your issue came directly from GitHub without referencing the document you are referrring to.) If you can provide an URL we can start there. Thank you

**Comment by jremmc** [comment]
Guess I was not specific enough, here's link: https://docs.microsoft.com/en-us/exchange/collaboration/public-folders/batch-migration-from-previous-versions?view=exchserver-2019 - I used link from that article to get here (to GitHub), I thought it would take me directly to comments for that specific document.

**Comment by nenonix** [comment]
@jremmc Thanks. Not sure why the article wasn't referenced but now we are on the same page. As a writer I can always use more specifics :) on how you think we can edit the document but I will get back to you if I can't figure it out from here.

**Comment by dariomws306** [comment]
Hi @jremmc , thanks for you feedback.

I have updated the command, now this will identify the migration mailbox and where it's placed.

About the reason to look for \ and / is because if you don't remove them from the public folders name, it will create the PFs on the parent directory in Exchange 2016.

"Get-PublicFolder -Recurse" doesn't return system public folders by default (you should use "Get-PublicFolder -Identity \NON_IPM_SUBTREE -Recurse"), and I think it's intentionally because you don't need to migrate Exchange 2010 system public folders to 2010 (OAB, free/busy).
