### ISSUE TITLE
Wrong Link for Use batch migration to migrate Exchange 2013 public folders to Office 365 Groups

### ISSUE THREAD

**Issue by TylerRosolowski** [MicrosoftDocs/OfficeDocs-Exchange#51]
This link, links to Exchange 2016 public folders to Office 365 Groups

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b90acf0-7679-cc85-c2a3-5993fe0a4e96
* Version Independent ID: 7b7cb9b1-f04d-c5c9-0dcd-180aa5b50c18
* Content: [Migrate your public folders to Office 365 Groups](https://docs.microsoft.com/en-us/exchange/collaboration-exo/public-folders/migrate-your-public-folders-to-office-365-groups)
* Content Source: [Exchange/ExchangeOnline/collaboration-exo/public-folders/migrate-your-public-folders-to-office-365-groups.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/collaboration-exo/public-folders/migrate-your-public-folders-to-office-365-groups.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by kenwith** [comment]
@TylerRosolowski - Thank you for submitting this feedback.

I have captured this as a bug and added it into the backlog for the Exchange team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated.

I made a note to request the team to update this when the work is complete.

**Comment by TylerRosolowski** [comment]
Thanks for the quick response. The link is still wrong, is there some time we wait for the site to be updated?

**Comment by kenwith** [comment]
I added it to the backlog so the writing team can get this addressed. I am not positive on the links and where they should go. If you know I can guide you through submitting a Pull Request to fix the article and then get that approved by the writing team or I can take a stab if you can tell me what you think it should be. Otherwise we can wait until the writing team gets it into their sprint plan to get this fixed. Thanks for engagement on this and making the docs better. Much appreciated.

PS - I just close these for housekeeping. The item is captured in the writing teams backlog. You, or anyone, can reply at any time and it will re-open the issue automatically.

**Comment by chrisda** [comment]
@TylerRosolowski the link is fixed now.
