### ISSUE TITLE
Good first step

### ISSUE THREAD

**Issue by jdkc4d** [MicrosoftDocs/OfficeDocs-Exchange#554]
As a 2nd step, I would like to see the opposite as well. Emails that come in from non-tenant email addresses should come with a banner at the top indicating that it is an outside email and to be careful in case its spam. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76073a9f-750e-fe8d-cc6b-e74a76e82f5b
* Version Independent ID: 5857e1e1-0d71-b005-98c2-ab99d4609200
* Content: [Deploying Outlook for iOS and Android app configuration settings](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune#general-app-configuration-settings)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/outlook-for-ios-and-android/outlook-for-ios-and-android-configuration-with-microsoft-intune.md)
* Service: **exchange-online**
* Product: **exchange**
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by j0rt3g4** [comment]
Hi, @jdkc4d  here's no mention of the word "banner" in the whole article you mentioned, can you let me know where you want to see the second step implemented? since there's nothing related what you report with the configuration you referenced  "* outlook-for-ios-and-android-configuration-with-microsoft-intune.md" could you please clarify where is this banner flag?

**Comment by jdkc4d** [comment]
Hey Jose,

Take a look at this image from MC172761. When someone on outlook mobile
goes to respond, it puts this little yellow banner at the top showing that
they are replying to external email accounts. It would be great if it did
the same thing when they received emails. A lot of people in my
organization will still forward spam to me, freaking out because they think
something with a fake office365 logo is a legit thing telling them their
account is going to be closed or shut down or something. If they got a
similar banner when they received messages from outside the organization,
it might go a long way to preventing non-technical folks from clicking on
something that technically minded folks like you or I can easily deduce to
be spam or a phishing attempt.


[image: image.png]

**Comment by j0rt3g4** [comment]
Im unable to see the image it just says [image_image.png]
attack a link pls? :)

**Comment by jdkc4d** [comment]
http://joshkelahan.com/bhhs/OutlookMobileBanner.PNG

**Comment by j0rt3g4** [comment]
I see,
try this
https://newsignature.com/articles/dont-send-that-enable-mailtip-for-external-recipients-in-office-365/

**Comment by jdkc4d** [comment]
Again, this is about the recipient, when you are sending a message. I am
talking about when you receive a message.

**Comment by j0rt3g4** [comment]
That box with messages is called "Mailtip" and is just implemented on the "Sending" stage not on the receiving, so this issue is more a request to implement features than an error in the documentation itself, that process can't be done.

For support you can use this:
https://support.office.com/home/contact

Or add a new idea you can use the User'sVoice 
https://outlook.uservoice.com/forums/322590-outlook-2016-for-windows/search?filter=hot&oauth_consumer_key=mZUyUjsGInIPk9fwULg&query=mailtip

And finally Ask the community:
https://answers.microsoft.com/en-us/msoffice/forum?sort=LastReplyDate&dir=Desc&tab=All&status=all&mod=&modAge=&advFil=&postedAfter=&postedBefore=&threadType=All&isFilterExpanded=false&page=1
https://answers.microsoft.com/en-us/msoffice/forum
