### ISSUE TITLE
How does an Exchange Admin know the command worked?

### ISSUE THREAD

**Issue by SeaGT** [MicrosoftDocs/OfficeDocs-Exchange#567]
Where is a report or a value set that tells an Admin that this command is running on a regular basis and on which mailboxes and what the results were?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 767ba6af-482f-49da-9e83-0a2aeaf9f559
* Version Independent ID: e07f25b1-0afd-50f9-b62a-55617d06cb68
* Content: [Configure and run the Managed Folder Assistant in Exchange Server](https://docs.microsoft.com/en-us/exchange/policy-and-compliance/mrm/configure-managed-folder-assistant?view=exchserver-2019)
* Content Source: [Exchange/ExchangeServer/policy-and-compliance/mrm/configure-managed-folder-assistant.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/policy-and-compliance/mrm/configure-managed-folder-assistant.md)
* Product: **exchange-server-it-pro**
* GitHub Login: @SerdarSoysal
* Microsoft Alias: **serdars**

**Comment by j0rt3g4** [comment]
Hi @SeaGT as the article says, all the mailboxes are being processed by MFA once a day, there's no such a thing like a report where you are being told that MFA is running on a regular basis, so there's no way to troubleshoot it since it's a daily task report or any historical information about it.

The MFA runs every day at least you override the settings using the "New-SettingOverride" cmdlet

In the section "how do you know this worked" there's an XML that can be used to
A little correction on the "How do you know this worked?".

This is an unmanaged process that's the main reason why you don't have any sort of information regarding to the mailboxes, who ran the cmdlet, you need special permissions to run these cmdlets so the person who has those rights can be constantly forcing the MFA on the server. Like any other cmdlet, there's no registry on who's running it, which mailboxes were these cmdlets run against or what were the results.

**Comment by SeaGT** [comment]
j0rt3g4 -thanks for the reply but that doesn't do me any good.  If the MFA ran successfully on Bob's mailbox, then I'd like to see a report of how much email was transferred to the archive folders or deleted or purged.  If it was 0 - that great - at least I know it ran.
You mentioned that the MFA ran as a daily task, but my understanding is that the MFA runs on a mailbox every 7 days but I can force it to run on a mailbox with a powershell command.  So if it is a max of 7 days between running on my mailboxes, if I had a report of what was processed on the last run I could see when the MFA might run again...  
 Without a report - how do I know if the retention tags are working or not?  Other than me going in every day and running powershell commands against the mailbox and even then, I don't know if the MFA reduced the size of the mailbox (so my retention policy and tags are working) or if the user got fed up with the "running out of space messages" and deleted a lot of emails.
If we get taken to court and I can show the judge that this mailbox had "X" amount of email deleted on this day from this mailbox, I would think that is reasonable proof that our retention policy is being followed.

**Comment by j0rt3g4** [comment]
@SeaGT  This is a request on features is not a lack of documentation. So the idea of these issues is to fix or add information that is missing on the documentation. The request for additional features that are not "live" is made thru the user's voice chat. 
https://office365.uservoice.com/
