### ISSUE TITLE
Information in this page in Inaccurate and wrong

### ISSUE THREAD

**Issue by y-kholusi** [MicrosoftDocs/OfficeDocs-Exchange#797]
The virtual directory setting listed in this page is not for "Default Web Site" but for "Exchnge Back End". It should be for "Default Web Site"
Also setting talked about like "The only virtual directories that don't have Require SSL enabled by default are /IES, /PowerShell, and /Rpc." is for "Exchnge Back End".
in "Default Web Site", /Rpc virtual directory is Require SSL enabled that referenced in "https://docs.microsoft.com/en-us/exchange/clients/default-virtual-directory-settings?view=exchserver-2016" correctly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bad6b073-061b-60d6-958c-e3f408aebf85
* Version Independent ID: 19356060-5edf-5eb7-6abc-97c4fc741bd5
* Content: [Configure http to https redirection for Outlook on the web in Exchange Server](https://docs.microsoft.com/en-us/exchange/clients/outlook-on-the-web/http-to-https-redirection?view=exchserver-2016#feedback)
* Content Source: [Exchange/ExchangeServer/clients/outlook-on-the-web/http-to-https-redirection.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeServer/clients/outlook-on-the-web/http-to-https-redirection.md)
* Product: **exchange-server-it-pro**
* Technology: ****
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by chrisda** [comment]
@y-kholusi, the screenshots and information in the topic is only talking about the Default Web Site -- not Exchange Back End. I used a current Exchange 2016 on Windows 2012 R2 test server that has never been modified for http/https redirection, and the information in the table in the section at the end 100% matches what I see on my server.

Just for fun, I also looked on an Exchange 2013 server on Win 2012 R2, and an Exchange 2019 server on Win 2016. For all of them, the RPC virtual directory in the Default Web Site does not require SSL (Require SSL is unchecked).

What I also found: the second topic you referenced [Default settings for Exchange virtual directories](https://docs.microsoft.comexchange/clients/default-virtual-directory-settings) has been around since Exchange 2010 (at least), and I can confirm that on an Exchange 2010 server on Windows 2008 R2, the Rpc virtual directory in the Default Web Site *does* has Require SSL checked. But, the server architectures are different (there is no front end/back end), so it's not a fair comparison. So, I think based on what I'm seeing in Exchange 2013, 2016, and 2019, the information about Rpc in that second topic is wrong.

Can you clarify?

**Comment by y-kholusi** [comment]
@chrisda 
I'm understand that the information in this article is about "Default Web Site". 
I think two problem is here.
problem 1:
I use "?view=exchserver-2016" at the end of the link so I expect to see Exchange 2016 product information. 
The screenshots of  "Default Web Site" in article show "_wmcs", "IES" directory in "Default Web Site". 
Also in text it say "The only virtual directories that don't have Require SSL enabled by default are /IES, /PowerShell, and /Rpc." and in table at the end of article it again list "_wmcs", "IES" directory.
I could not found any of this directory in "Default Web Site" of my installed Exchange 2016.
I understand that this article share between product versions. may be I expect too much accuracy here but this kind of information doubt users that they have something wrong with their installation.
problem 2:
We both agree that there was some mismatch information about "SSL required" between this article and the one in "https://docs.microsoft.com/en-us/exchange/clients/default-virtual-directory-settings?view=exchserver-2016" that I think it is resolved now.
Just again the "_wmcs" and "IES" listed in this article (Configure http to https redirection...) table not listed in the "Default settings for Exchange virtual directories" article that I think the "Default settings for Exchange virtual directories" article is accurate about this.

**Comment by chrisda** [comment]
@y-kholusi, ah OK. When I was correcting the [Default settings for Exchange virtual directories](https://docs.microsoft.comexchange/clients/default-virtual-directory-settings) topic, I, too, noticed that there were missing virtual directories in that topic. But, the purpose of that topic is *Exchange* virtual directories. The http/https redirection topic requires you to change the SSL settings on the Default Web Site, and that affects **all** virtual directories under that web site (whether they are Windows, Exchange, etc.).

In short, I'm OK with those two topics not listing the same virtual directories, because the http/https redirect topic also lists Windows virtual directories, and doesn't talk about the Exchange Back End virtual directories at all. But, for those virtual directories that are in common between the two topics, they shouldn't contain conflicting about SSL settings (the Rpc vdir did, but I fixed it).

I am curious about your lack of _wmcs and IES in the Default Web Site. What version of Windows Server are you running? The issue might be caused by an unrelated Windows feature that's installed or not installed on my end. I can always add a note that these vdirs might not be present in your environment.

**Comment by y-kholusi** [comment]
@chrisda
My last installation is Exchange Server 2016 CU 12 on Windows Server 2016 Build 10.0.14393.
I attach an screenshot of what I have in both Default Web Site and Exchange Back End.
![Server2016-Exchange2016-CU12](https://user-images.githubusercontent.com/49610613/56232134-4e34fd80-6095-11e9-9e6f-00d43ad91a4a.png)

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrisda** [comment]
@y-kholusi I removed the _wmcs and IES vdirs from the text and from the screenshots so the Default Web Site in the topic now looks like yours.

Thanks for the feedback
