### ISSUE TITLE
Remote Domains vs Accepted Domains

### ISSUE THREAD

**Issue by terrogin** [MicrosoftDocs/OfficeDocs-Exchange#820]
I've been testing MailTips for external recipients, and I have no remote domains configured, but I do have accepted domains. Based on the article, I assumed sending to another domain not in the Remote Domains list would treat the recipient as external, but if the domain is in the Accepted Domains list and not in the Remote Domains list, they seem to be treated as internal anyway. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c34a8f0-2eca-250c-f85a-b1b53e7f0ec9
* Version Independent ID: 0bbb9cef-0e4b-6107-5eac-41e5ee3e1f89
* Content: [MailTips](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/mailtips/mailtips)
* Content Source: [Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/mailtips/mailtips.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/clients-and-mobile-in-exchange-online/mailtips/mailtips.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @msdmaguire
* Microsoft Alias: **dmaguire**

**Comment by chrisda** [comment]
@terrogin, I updated the topic for clarity.

Accepted domains (authoritative or internal relay) are always treated as internal domains. Remote domains are designed for external domains, but you can use the IsInternal parameter to treat them like internal domains, and there's nothing stopping you from configuring a remote domain for an accepted domain (why you would do this is another story). And, every organization has a default remote domain named Default for address space * that affects all messages to external domains that aren't otherwise defined in a specific remote domain.

So, in a typical setup with one or more accepted domains and no specific remote domains other than Default, recipients in the accepted domains are treated as internal, and all other recipients are treated as external.
