### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by EnglishIrishman** [MicrosoftDocs/OfficeDocs-Exchange#935]
![Capture](https://user-images.githubusercontent.com/50587840/57631852-2ce20700-7598-11e9-89f0-c93e12a1e5d0.PNG)

The tooltip for 'Send As' has the word 'apppear' instead of 'appear'

**Comment by scanum** [comment]
@EnglishIrishman Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by scanum** [comment]
@EnglishIrishman Thank you for submitting feedback. Since this is not a documentation error and it is more at the product level.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
