### ISSUE TITLE
admin who perform ediscovery search need to have EXO license and EXO mailbox(valid SMTP address)

### ISSUE THREAD

**Issue by limin365** [MicrosoftDocs/OfficeDocs-Exchange#973]
admin who perform ediscovery search need to have EXO license and EXO mailbox(valid SMTP address)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00fed962-98a7-b792-a393-1e6b529f5a4b
* Version Independent ID: 30bc103b-3e7e-2e99-f5bf-b75f59d3fa4b
* Content: [In-Place eDiscovery](https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-ediscovery/in-place-ediscovery#feedback)
* Content Source: [Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/in-place-ediscovery.md](https://github.com/MicrosoftDocs/OfficeDocs-Exchange/blob/public/Exchange/ExchangeOnline/security-and-compliance/in-place-ediscovery/in-place-ediscovery.md)
* Service: **exchange-online**
* Product: **exchange**
* Technology: ****
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@limin365 - This requirement is documented in the topic on how to create an in-place ediscovery search: https://docs.microsoft.com/en-us/exchange/security-and-compliance/in-place-ediscovery/create-in-place-ediscovery-search#what-do-you-need-to-know-before-you-begin

"To create eDiscovery searches, you have to have an SMTP address in the organization that you're creating the searches in. So in Exchange Online, you must have a licensed Exchange Online (Plan 2) mailbox to create eDiscovery searches. In an Exchange hybrid organization, your on-premises Exchange mailbox must have a corresponding mail user account in your Office 365 organization so that you can search Exchange Online mailboxes. Or, if you sign in with an account that only exists in Office 365, such as the tenant administrator account, that account must be assigned an Exchange Online (Plan 2) license."
